"""TEST-S3-ASR-U5-ORACLE: vectors and tagged mutants for tests/dictation_refusal_oracle.py.

Stdlib only: no stack, no browser, no .env. `python -B tests/dictation_refusal_oracle_test.py`
- 26 canonical observations pass, and each is restated here literally rather than generated by the oracle;
- every mutant must produce exactly its expected tag set (another tag does not count), and is printed
  as one MUTANT line with what was expected and what was observed;
- the expected messages are bound to their api/src lines at the pin, and the live battery's wiring in
  tests/invariants_live.py is pinned by parsing it (it is never imported: that loads .env).
"""
import ast
import copy
import hashlib
import json
from pathlib import Path
import sys
import unittest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tests"))
import dictation_refusal_oracle as u5

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass


def source(relative):
    return (ROOT / relative).read_text(encoding="utf-8").replace("\r\n", "\n")


PIN = u5.source_engine_pin(source("api/src/asr.service.ts"))
ACTORS = {name: "kin-test-000000000000-%s@local.test" % name
          for name in ("doctor", "doctor2", "jmryu", "tech", "kdoctor")}
SECRET = "REPORT-" + "0" * 32
CONTEXT = {"engine_pin": PIN, "secret": SECRET, "actors": ACTORS,
           "holder": ACTORS["doctor"], "pre_reviewer": ACTORS["jmryu"]}
UID, PROBE = "1.2.826.0.1.3680043.8.498.1", "2.25.1"


def nest(status, error, message):
    return {"message": message, "error": error, "statusCode": status}


def coded(code):
    return {"code": code, "message": code}


# The accepted contract, restated literally (draft sections 4-5 with amendments A2/A3).
ROLE_403 = (403, nest(403, "Forbidden", "판독문 저장은(는) radiologist 권한이 필요합니다"))
ADMITTED = (503, coded("DICTATION_NOT_CONFIGURED"))
NOT_FOUND = (404, nest(404, "Not Found", "검사를 찾을 수 없습니다"))
LITERAL = {
    "C-W": ADMITTED, "R-ROLE": ROLE_403, "R-ROLE-CT": ROLE_403, "R-ROLE-BIG": ROLE_403,
    "R-UNAUTH": (401, nest(401, "Unauthorized", "인증 정보가 없습니다")),
    "R-GATEWAY": (403, nest(403, "Forbidden", "게이트웨이에 허용되지 않는 경로입니다")),
    "I-CT": (400, coded("DICTATION_AUDIO_INVALID")), "I-ENC": (400, coded("DICTATION_AUDIO_INVALID")),
    "I-FMT": (400, coded("DICTATION_AUDIO_INVALID")), "I-BIG": (413, coded("DICTATION_AUDIO_TOO_LARGE")),
    "C-W2": ADMITTED,
    "R-HELD": (409, {"code": "REPORT_HELD", "holder": ACTORS["doctor"],
                     "message": ACTORS["doctor"] + " 님이 판독 중입니다"}),
    "C-HOLDER": ADMITTED, "C-EXPIRED": ADMITTED,
    "R-PRELIM": (403, nest(403, "Forbidden",
                           "예비 판독(RS: P) 중입니다. " + ACTORS["jmryu"] + "만 이어서 판독할 수 있습니다.")),
    "C-P-AUTHOR": ADMITTED, "C-P-REVIEWER": ADMITTED,
    "R-UNVERIFIED": (409, nest(409, "Conflict", "촬영 중(미확인) 검사입니다 — 기사 확인(Verify) 뒤 판독할 수 있습니다")),
    "C-EMERGENCY": ADMITTED,
    "R-TENANT": NOT_FOUND, "C-TELE": ADMITTED, "R-NOSTATE": NOT_FOUND,
    "R-CSRF": (403, nest(403, "Forbidden", "X-KIN-CSRF 헤더가 필요합니다")),
    "R-FORGED": (401, nest(401, "Unauthorized", "인증 세션이 없습니다")),
    "C-SESSION": ADMITTED, "C-A": ADMITTED,
}
CONTROL_AUDIT = (46, 0.0000625, "DICTATION_NOT_CONFIGURED")
AUDIT = {case_id: CONTROL_AUDIT for case_id, answer in LITERAL.items() if answer is ADMITTED}
AUDIT.update({"I-CT": (0, 0, "DICTATION_AUDIO_INVALID"), "I-ENC": (0, 0, "DICTATION_AUDIO_INVALID"),
              "I-FMT": (46, 0, "DICTATION_AUDIO_INVALID"), "I-BIG": (0, 0, "DICTATION_AUDIO_TOO_LARGE")})
TABLE = {   # (id, kind, caller, pair), in call order
    "T1": [("C-W", "control", "doctor", None), ("R-ROLE", "refusal", "tech", "C-W"),
           ("R-ROLE-CT", "refusal", "tech", "C-W"), ("R-ROLE-BIG", "refusal", "tech", "C-W"),
           ("R-UNAUTH", "refusal", None, "C-W"), ("R-GATEWAY", "refusal", "gateway", "C-W")],
    "T2": [("I-CT", "input", "doctor", "C-W2"), ("I-ENC", "input", "doctor", "C-W2"),
           ("I-FMT", "input", "doctor", "C-W2"), ("I-BIG", "input", "doctor", "C-W2"),
           ("C-W2", "control", "doctor", None)],
    "T3": [("R-HELD", "refusal", "doctor2", "C-EXPIRED"), ("C-HOLDER", "control", "doctor", None),
           ("C-EXPIRED", "control", "doctor2", None)],
    "T4": [("R-PRELIM", "refusal", "doctor2", "C-P-AUTHOR"), ("C-P-AUTHOR", "control", "doctor", None),
           ("C-P-REVIEWER", "control", "jmryu", None)],
    "T5": [("R-UNVERIFIED", "refusal", "doctor", "C-EMERGENCY"), ("C-EMERGENCY", "control", "doctor", None)],
    "T6": [("R-TENANT", "refusal", "kdoctor", "C-TELE"), ("C-TELE", "control", "kdoctor", None),
           ("R-NOSTATE", "refusal", "doctor", "C-TELE")],
    "T7": [("R-CSRF", "refusal", "doctor", "C-SESSION"), ("R-FORGED", "refusal", None, "C-SESSION"),
           ("C-SESSION", "control", "doctor", None)],
    "T8": [("C-A", "control", "doctor2", None)],
}
CALLER = {row[0]: row[2] for rows in TABLE.values() for row in rows}
TEST_NAMES = {
    "T1": ("LiveInvariantTests", "test_dictation_u5_01_role_guard_and_parser_order"),
    "T2": ("LiveInvariantTests", "test_dictation_u5_02_input_refusals_after_the_gate"),
    "T3": ("LiveInvariantTests", "test_dictation_u5_03_hold_refuses_other_actor_and_is_untouched"),
    "T4": ("LiveInvariantTests", "test_dictation_u5_04_preliminary_third_party_refused"),
    "T5": ("LiveInvariantTests", "test_dictation_u5_05_filming_non_emergency_refused"),
    "T6": ("LiveInvariantTests", "test_dictation_u5_06_institution_follows_tele_visibility"),
    "T7": ("BffInvariantTests", "test_dictation_u5_07_cookie_session_csrf"),
    "T8": ("LiveInvariantTests", "test_dictation_u5_08_approved_report_parity"),
}

STAMP = "2026-09-24T00:00:00.000"
REPORT = {"uid": UID, "findings": SECRET, "conclusion": "approved", "recommendation": "none", "version": 1,
          "updatedBy": ACTORS["doctor"], "updatedAt": STAMP}
VERSION = {"id": 7, "uid": UID, "version": 1, "action": "approve", "findings": SECRET, "conclusion": "approved",
           "recommendation": "none", "reason": None, "author": ACTORS["doctor"], "citations": None,
           "structured": None, "at": STAMP}
ROWS = {"T4": {"report": dict(REPORT, version=0), "drafts": [], "versions": [dict(VERSION, action="preliminary")]},
        "T8": {"report": REPORT, "drafts": [], "versions": [VERSION]}}
STATE_CHANGES = {
    "R-HELD": {"holder": ACTORS["doctor"], "heldAt": STAMP}, "C-HOLDER": {"holder": ACTORS["doctor"], "heldAt": STAMP},
    "C-EXPIRED": {"holder": ACTORS["doctor"], "heldAt": "2026-09-23T23:54:00.000"},
    "R-PRELIM": {"rs": "P", "preDoc": ACTORS["doctor"], "preReviewer": ACTORS["jmryu"]},
    "R-UNVERIFIED": {"ss": "Unverified"}, "C-EMERGENCY": {"ss": "Unverified", "em": "E"},
    "C-TELE": {"ts": "wait", "teleInstitutionId": "kin-center"}, "C-A": {"rs": "A", "repDoc": ACTORS["doctor"]},
}
STATE_CHANGES["C-P-AUTHOR"] = STATE_CHANGES["C-P-REVIEWER"] = STATE_CHANGES["R-PRELIM"]


def state_row(**changes):
    row = {"uid": UID, "institutionId": "hallym", "teleInstitutionId": None, "origin": "dicom", "rs": "W",
           "holdReason": None, "ss": "Verified", "em": "N", "ts": "none", "matched": "U", "ward": "",
           "reqHosp": "KIN", "repDoc": None, "confirm": None, "preDoc": None, "preReviewer": None, "ov": None,
           "orig": None, "orderOid": None, "holder": None, "heldAt": None, "updatedAt": STAMP, "createdAt": STAMP}
    row.update(changes)
    return row


def audit_row(case_id, detail=None, **changes):
    """The row the API writes, with the detail text as JavaScript serializes it (0.0000625, not 6.25e-05)."""
    size, seconds, outcome = AUDIT[case_id]
    text = ('{"bytes":%d,"seconds":%s,"ms":3,"engine":"%s","outcome":"%s"}'
            % (size, "0.0000625" if seconds else "0", PIN, outcome)) if detail is None else json.dumps(detail)
    row = {"id": 901, "at": "2026-09-24T00:00:01.000", "actor": ACTORS[CALLER[case_id]],
           "action": "dictation.request", "target": UID, "detail": text}
    row.update(changes)
    return row


def stray_row(case_id, action="dictation.request"):
    return {"id": 901, "at": "2026-09-24T00:00:01.000", "actor": ACTORS.get(CALLER[case_id]) or "unknown",
            "action": action, "target": UID, "detail": '{"bytes":46}'}


def canonical(case_id):
    case = u5.CASE_BY_ID[case_id]
    status, body = LITERAL[case_id]
    rows = copy.deepcopy(ROWS.get(case.test, {"report": None, "drafts": [], "versions": []}))
    before = {"audit_max": 900, "audit_total": 0 if case.probe else 4, "audit": [],
              "state": None if case.probe else state_row(**STATE_CHANGES.get(case_id, {})), **rows}
    after = copy.deepcopy(before)
    if case_id in AUDIT:
        after["audit"], after["audit_total"] = [audit_row(case_id)], before["audit_total"] + 1
    return {"id": case_id, "status": status, "body": copy.deepcopy(body),
            "text": json.dumps(body, ensure_ascii=False), "cache_control": "no-store",
            "before": before, "after": after}


def detail_of(case_id):
    size, seconds, outcome = AUDIT[case_id]
    return {"bytes": size, "seconds": seconds, "ms": 3, "engine": PIN, "outcome": outcome}


VECTORS, MUTANTS = [], []


class OracleTests(unittest.TestCase):
    def kill(self, name, observed, expected, order=u5.TAGS):
        self.assertTrue(expected and set(expected) <= set(order), "badly declared mutant: " + name)
        expected = [tag for tag in order if tag in set(expected)]
        observed = list(observed)
        MUTANTS.append((name, expected, observed))
        print("MUTANT " + json.dumps({"name": name, "expected": expected, "observed": observed}), flush=True)
        self.assertEqual(observed, expected, name)

    def mutate(self, case_id, change, context=CONTEXT):
        observed = canonical(case_id)
        change(observed)
        return u5.case_problems(case_id, observed, context)

    def test_01_case_table_is_the_accepted_contract(self):
        self.assertEqual(len(u5.CASES), 26)
        self.assertEqual(len({case.id for case in u5.CASES}), 26)
        self.assertEqual({kind: sum(case.kind == kind for case in u5.CASES) for kind in u5.KINDS},
                         {"refusal": 12, "input": 4, "control": 10})
        self.assertEqual(u5.TESTS, TEST_NAMES)
        for test, rows in TABLE.items():
            self.assertEqual([(case.id, case.kind, case.caller, case.pair) for case in u5.CASES if case.test == test],
                             rows, test)
            self.assertEqual(u5.case_ids(test), [row[0] for row in rows])
        for case in u5.CASES:
            with self.subTest(case=case.id):
                self.assertEqual(case.status, LITERAL[case.id][0])
                self.assertEqual(case.audit, AUDIT.get(case.id))
                self.assertEqual(case.audit is None, case.kind == "refusal")
                self.assertEqual(case.probe, case.id == "R-NOSTATE")
                if case.pair is not None:   # credited only against a control of the same test
                    self.assertEqual((u5.CASE_BY_ID[case.pair].kind, u5.CASE_BY_ID[case.pair].test), ("control", case.test))
                self.assertEqual(case.pair is None, case.kind == "control")

    def test_02_expected_bodies_are_bound_to_the_source_at_the_pin(self):
        for case in u5.CASES:
            self.assertEqual(u5.expected_body(case, CONTEXT), LITERAL[case.id][1], case.id)
        pacs, guard = source("api/src/pacs.service.ts"), source("api/src/auth.guard.ts")
        anchors = {
            "api/src/pacs.service.ts": [
                "throw new ForbiddenException(`${what}은(는) ${role} 권한이 필요합니다`);",
                "need(c.roles, 'radiologist', '판독문 저장');",
                "throw new ConflictException('촬영 중(미확인) 검사입니다 — 기사 확인(Verify) 뒤 판독할 수 있습니다');",
                "throw new ConflictException({ code: 'REPORT_HELD', holder: heldByOther, message: `${heldByOther} 님이 판독 중입니다` });",
                "if (!prev) throw new NotFoundException('검사를 찾을 수 없습니다');",
                "`예비 판독(RS: P) 중입니다. ${prev?.preReviewer ?? '지정된 판독의'}만 이어서 판독할 수 있습니다.`);",
                "return this.scopeWrite(uid, c, async tx => { await this.reportDraftGate(uid, c, tx); });",
                "await this.audit(c.actor, 'dictation.request', uid, detail);",
            ],
            "api/src/auth.guard.ts": [
                "if (!raw) throw new UnauthorizedException('인증 정보가 없습니다');",
                "throw new ForbiddenException({ code: 'GATEWAY_IDENTITY_INVALID' });",
                "throw new ForbiddenException('게이트웨이에 허용되지 않는 경로입니다');",
                "throw new ForbiddenException('X-KIN-CSRF 헤더가 필요합니다');",
            ],
            "api/src/auth.service.ts": ["throw new UnauthorizedException('인증 세션이 없습니다');"],
            "api/src/asr.service.ts": ["return new HttpException({ code, message: code }, status);",
                                       "if (!config.available) throw dictationError('DICTATION_NOT_CONFIGURED');"],
            "api/src/dictation-audio.ts": ["export const DICTATION_AUDIO_MAX_BYTES = 1_048_576;",
                                           "export const DICTATION_SAMPLE_RATE = 16_000;"],
            "api/src/dictation-parser.ts": ["res.setHeader('Cache-Control', 'no-store');", "req.body = Buffer.alloc(0);"],
            "api/src/dictation.controller.ts": [
                "const bytes = Buffer.isBuffer(req.body) ? req.body : Buffer.alloc(0);",
                "await this.pacs.dictationAudit(uid, caller, { bytes: bytes.length, seconds: audio.ok ? audio.seconds : 0,",
                "ms: Date.now() - started, engine: this.asr.capability().enginePin, outcome });",
            ],
        }
        for relative, snippets in anchors.items():
            text = source(relative)
            for snippet in snippets:
                self.assertIn(snippet, text, relative)
        self.assertEqual("${what}은(는) ${role} 권한이 필요합니다".replace("${what}", "판독문 저장")
                         .replace("${role}", "radiologist"), u5.ROLE)
        # Refusal order at the pin: role, institution, filming, hold, no row, prelim; the first gate call
        # sits outside the audited try, and the audit's keys are exactly the controller's five.
        gate = pacs[pacs.index("private async reportDraftGate("):pacs.index("async dictationGate(")]
        order = ["need(c.roles, 'radiologist'", "this.gate(uid,c,tx)", "prev?.ss === 'Unverified'",
                 "REPORT_HELD", "if (!prev)", "canReadPrelim(prev, c.actor)"]
        self.assertEqual([gate.index(part) for part in order], sorted(gate.index(part) for part in order))
        controller = source("api/src/dictation.controller.ts")
        self.assertLess(controller.index("await this.pacs.dictationGate(uid, caller);"),
                        controller.index("let outcome = 'DICTATION_ENGINE_FAILED';"))
        self.assertLess(guard.index("'인증 정보가 없습니다'"), guard.index("'X-KIN-CSRF 헤더가 필요합니다'"))
        self.assertEqual(set(u5.AUDIT_KEYS), {"bytes", "seconds", "ms", "engine", "outcome"})
        self.assertTrue(PIN and PIN.startswith("whisper.cpp@"), PIN)
        self.assertEqual(u5.MAX_BYTES, 1048576)

    def test_03_wav_fixtures_are_the_pinned_bytes(self):
        wave, other, big = u5.wav(), u5.wav(44100), u5.oversized()
        self.assertEqual((len(wave), hashlib.sha256(wave).hexdigest()),
                         (46, "156075e2635b9b2c186258f4db987ed9fbdfb727f49e5eac4b9a126aefbdf727"))
        self.assertEqual((len(other), hashlib.sha256(other).hexdigest()),
                         (46, "48f304b4730189540fb9a2b9c8d05d6aba5e55b1375efbd9e2ef28ed544a9743"))
        self.assertEqual((u5.WAV_SHA256, u5.WAV_44100_SHA256),
                         (hashlib.sha256(wave).hexdigest(), hashlib.sha256(other).hexdigest()))
        changed = [i for i in range(46) if wave[i] != other[i]]
        self.assertTrue(changed and set(changed) <= set(range(24, 32)), changed)   # only the two rate fields
        self.assertEqual((len(big), set(big)), (1048577, {0}))
        # Same bytes as the existing REPORT battery's dictation call (invariants_live.call_report_route).
        self.assertIn('struct.pack("<IHHIIHH", 16, 1, 1, 16000, 32000, 2, 16)', source("tests/invariants_live.py"))

    def test_04_canonical_observations_pass(self):
        lines = []
        for case in u5.CASES:
            self.assertEqual(u5.case_problems(case.id, canonical(case.id), CONTEXT), [], case.id)
            VECTORS.append(case.id)
        for test in TABLE:
            got = u5.evaluate(test, [canonical(case_id) for case_id in u5.case_ids(test)], CONTEXT)
            self.assertEqual([(line["id"], line["problems"]) for line in got], [(case_id, []) for case_id in u5.case_ids(test)])
            self.assertTrue(all(set(line) == u5.LINE_KEYS for line in got))
            lines += got
        good = [u5.precondition(test, self.capability(), PIN, u5.wav()) for test in TABLE]
        self.assertEqual([line["problems"] for line in good], [[]] * 8)
        report = u5.summary(lines, good)
        self.assertEqual((report["complete"], report["executed_cases"], report["kinds"]),
                         (True, 26, {"refusal": 12, "input": 4, "control": 10}))

    @staticmethod
    def capability(**changes):
        cap = {"available": False, "maxBytes": 1048576, "timeoutMs": 120000, "languagePin": "auto",
               "enginePin": PIN, "modelPin": "ggml-small@sha256:" + "0" * 64}
        cap.update(changes)
        return cap

    def test_05_every_case_fails_on_status_and_audit_delta(self):
        for case in u5.CASES:
            wrong = 200 if case.kind == "control" else 503
            self.kill(case.id + "/status", self.mutate(case.id, lambda o: o.update(status=wrong)), ["status"])
            if case.kind == "refusal":
                self.kill(case.id + "/audit-delta-1", self.mutate(
                    case.id, lambda o: o["after"]["audit"].append(stray_row(case.id))), ["audit-delta"])
                self.kill(case.id + "/audit-delta-other-action", self.mutate(
                    case.id, lambda o: o["after"]["audit"].append(stray_row(case.id, "report.draft"))), ["audit-delta"])
            else:
                self.kill(case.id + "/audit-delta-0", self.mutate(
                    case.id, lambda o: o["after"].update(audit=[])), ["audit-delta"])
                self.kill(case.id + "/audit-delta-2", self.mutate(
                    case.id, lambda o: o["after"]["audit"].append(audit_row(case.id, id=902))), ["audit-delta"])

    def test_06_every_case_fails_without_no_store_or_with_the_secret(self):
        for case in u5.CASES:
            self.kill(case.id + "/no-store-missing", self.mutate(case.id, lambda o: o.update(cache_control="")),
                      ["cache-control"])
            self.kill(case.id + "/no-store-twice", self.mutate(
                case.id, lambda o: o.update(cache_control="no-store, no-store")), ["cache-control"])
            self.kill(case.id + "/secret-in-text", self.mutate(
                case.id, lambda o: o.update(text=o["text"] + SECRET)), ["secret"])

    def test_07_audit_detail_drift_on_every_input_and_control(self):
        detail_tags = ["audit-keys", "audit-bytes", "audit-seconds", "audit-ms", "audit-engine", "audit-outcome"]
        for case in u5.CASES:
            if case.kind == "refusal":
                continue
            size, seconds, outcome = AUDIT[case.id]

            def detail(**changes):
                value = detail_of(case.id)
                value.update(changes)
                return lambda o: o["after"].update(audit=[audit_row(case.id, value)])

            without_engine = detail_of(case.id)
            del without_engine["engine"]
            mutants = [
                ("text-key", detail(text="synthetic words"), ["audit-keys"]),
                ("bytes+1", detail(bytes=size + 1), ["audit-bytes"]),
                ("bytes-as-text", detail(bytes=str(size)), ["audit-bytes"]),
                ("seconds", detail(seconds=0 if seconds else 0.0000625), ["audit-seconds"]),
                ("ms-negative", detail(ms=-1), ["audit-ms"]),
                ("ms-float", detail(ms=1.5), ["audit-ms"]),
                ("engine", detail(engine="whisper.cpp@0000000"), ["audit-engine"]),
                ("outcome", detail(outcome="success" if outcome == "DICTATION_NOT_CONFIGURED" else "DICTATION_NOT_CONFIGURED"),
                 ["audit-outcome"]),
                ("no-engine-key", lambda o: o["after"].update(audit=[audit_row(case.id, without_engine)]),
                 ["audit-keys", "audit-engine"]),
                ("actor", lambda o: o["after"].update(audit=[audit_row(case.id, actor=ACTORS["kdoctor"] + ".x")]),
                 ["audit-actor"]),
                ("action", lambda o: o["after"].update(audit=[audit_row(case.id, action="report.draft")]),
                 ["audit-action"]),
                ("detail-not-object", lambda o: o["after"].update(audit=[audit_row(case.id, "synthetic words")]),
                 detail_tags),
                ("detail-not-json", lambda o: o["after"].update(
                    audit=[dict(audit_row(case.id), detail="synthetic words")]), detail_tags),
                ("secret-in-detail", detail(text=SECRET), ["secret", "audit-keys"]),
            ]
            for name, change, expected in mutants:
                self.kill(case.id + "/" + name, self.mutate(case.id, change), expected)

    def test_08_rows_and_state_are_compared_around_every_call(self):
        for case in u5.CASES:
            probe = ["probe-rows"] if case.probe else []
            draft = {"uid": UID, "author": ACTORS["doctor"], "findings": "x", "conclusion": "", "recommendation": "",
                     "baseVersion": 0, "citations": None, "structured": None, "updatedAt": STAMP}
            self.kill(case.id + "/draft-written", self.mutate(
                case.id, lambda o: o["after"]["drafts"].append(draft)), ["report-rows"] + probe)
            self.kill(case.id + "/version-appended", self.mutate(
                case.id, lambda o: o["after"]["versions"].append(dict(VERSION, id=99, version=9))), ["report-rows"] + probe)
            self.kill(case.id + "/report-changed", self.mutate(
                case.id, lambda o: o["after"].update(report=dict(REPORT, findings="changed"))), ["report-rows"] + probe)
            self.kill(case.id + "/state-changed", self.mutate(
                case.id, lambda o: o["after"].update(state=state_row(holder=ACTORS["doctor2"], heldAt=STAMP))),
                ["study-state"] + probe)
            if not case.probe:
                self.kill(case.id + "/fixture-row-missing", self.mutate(
                    case.id, lambda o: (o["before"].update(state=None), o["after"].update(state=None))), ["study-state"])
            no_snapshot = ["audit-delta", "report-rows", "study-state"] + probe
            self.kill(case.id + "/no-after-snapshot", self.mutate(case.id, lambda o: o.update(after={})), no_snapshot)

    def test_09_named_product_defects_are_caught_by_their_case(self):
        """The declared kill map as observations: what each defect would make the live case see."""
        def admitted(case_id, actor_of):
            def change(o):
                o.update(status=503, body=coded("DICTATION_NOT_CONFIGURED"))
                o["after"]["audit"].append(dict(stray_row(case_id), actor=ACTORS[actor_of],
                                                detail='{"bytes":46,"seconds":0.0000625,"ms":3}'))
            return change

        def answered(status, body, drop_audit=False):
            def change(o):
                o.update(status=status, body=body)
                if drop_audit:
                    o["after"].update(audit=[])
            return change

        refused_and_admitted = ["status", "body", "audit-delta"]
        rows = [
            ("need-dropped", "R-ROLE", admitted("R-ROLE", "tech"), refused_and_admitted),
            ("parser-answers-ct", "R-ROLE-CT", answered(400, coded("DICTATION_AUDIO_INVALID")), ["status", "body"]),
            ("parser-answers-big", "R-ROLE-BIG", answered(413, coded("DICTATION_AUDIO_TOO_LARGE")), ["status", "body"]),
            ("parser-before-guard", "R-UNAUTH", answered(400, coded("DICTATION_AUDIO_INVALID")), ["status", "body"]),
            ("hold-check-dropped", "R-HELD", admitted("R-HELD", "doctor2"), refused_and_admitted),
            ("hold-ttl-ignored", "C-EXPIRED", answered(409, LITERAL["R-HELD"][1], True), refused_and_admitted),
            ("unverified-dropped", "R-UNVERIFIED", admitted("R-UNVERIFIED", "doctor"), refused_and_admitted),
            ("emergency-refused", "C-EMERGENCY", answered(*LITERAL["R-UNVERIFIED"], True), refused_and_admitted),
            ("prelim-dropped", "R-PRELIM", admitted("R-PRELIM", "doctor2"), refused_and_admitted),
            ("prelim-author-only", "C-P-REVIEWER", answered(*LITERAL["R-PRELIM"], True), refused_and_admitted),
            ("visible-dropped", "R-TENANT", admitted("R-TENANT", "kdoctor"), refused_and_admitted),
            ("tele-ignored", "C-TELE", answered(*NOT_FOUND, True), refused_and_admitted),
            ("csrf-exempted", "R-CSRF", admitted("R-CSRF", "doctor"), refused_and_admitted),
            ("gateway-invalid-identity-A3", "R-GATEWAY", answered(403, {"code": "GATEWAY_IDENTITY_INVALID"}), ["body"]),
            ("forged-expired-message-A2", "R-FORGED", answered(401, nest(401, "Unauthorized", "인증 세션이 만료되었습니다")),
             ["body"]),
            ("forged-cookie-not-sent", "R-FORGED", answered(401, nest(401, "Unauthorized", "인증 정보가 없습니다")), ["body"]),
            ("held-holder-swapped", "R-HELD", answered(409, dict(LITERAL["R-HELD"][1], holder=ACTORS["doctor2"])), ["body"]),
            ("prelim-reviewer-swapped", "R-PRELIM", answered(403, nest(
                403, "Forbidden", "예비 판독(RS: P) 중입니다. " + ACTORS["doctor2"] + "만 이어서 판독할 수 있습니다.")), ["body"]),
            ("prelim-leaks-findings", "R-PRELIM", answered(403, nest(403, "Forbidden", SECRET)), ["body", "secret"]),
            ("approved-leaks-findings", "C-A", answered(503, dict(coded("DICTATION_NOT_CONFIGURED"), text=SECRET)),
             ["body", "secret"]),
            ("session-other-actor", "C-SESSION",
             lambda o: o["after"].update(audit=[audit_row("C-SESSION", actor=ACTORS["doctor2"])]), ["audit-actor"]),
            ("holder-refreshed", "C-HOLDER", lambda o: o["after"]["state"].update(heldAt="2026-09-24T00:00:05.000"),
             ["study-state"]),
            ("expired-hold-taken", "C-EXPIRED", lambda o: o["after"]["state"].update(
                holder=ACTORS["doctor2"], heldAt="2026-09-24T00:00:05.000"), ["study-state"]),
            # A4: judged against a snapshot from before the backdate, the declared setup write looks like the call's.
            ("pre-backdate-snapshot-A4", "C-EXPIRED", lambda o: o["before"]["state"].update(heldAt=STAMP), ["study-state"]),
            ("validator-accepts-44100", "I-FMT", lambda o: (
                o.update(status=503, body=coded("DICTATION_NOT_CONFIGURED")),
                o["after"].update(audit=[audit_row("I-FMT", dict(detail_of("I-FMT"), seconds=1 / 44100,
                                                                 outcome="DICTATION_NOT_CONFIGURED"))])),
             ["status", "body", "audit-seconds", "audit-outcome"]),
            ("size-cap-raised", "I-BIG", lambda o: (
                o.update(status=400, body=coded("DICTATION_AUDIO_INVALID")),
                o["after"].update(audit=[audit_row("I-BIG", dict(detail_of("I-BIG"), bytes=1048577,
                                                                 outcome="DICTATION_AUDIO_INVALID"))])),
             ["status", "body", "audit-bytes", "audit-outcome"]),
            ("input-audit-dropped", "I-CT", lambda o: o["after"].update(audit=[]), ["audit-delta"]),
            ("nostate-row-created", "R-NOSTATE", lambda o: (
                o.update(status=503, body=coded("DICTATION_NOT_CONFIGURED")),
                o["after"].update(state=state_row(uid=PROBE), audit_total=1),
                o["after"]["audit"].append(stray_row("R-NOSTATE"))),
             ["status", "body", "audit-delta", "study-state", "probe-rows"]),
            ("nostate-old-audit", "R-NOSTATE", lambda o: (o["before"].update(audit_total=1),
                                                          o["after"].update(audit_total=1)), ["probe-rows"]),
        ]
        for name, case_id, change, expected in rows:
            self.kill(case_id + "/" + name, self.mutate(case_id, change), expected)
        without_holder = {key: value for key, value in CONTEXT.items() if key != "holder"}
        self.kill("R-HELD/context-without-holder", self.mutate("R-HELD", lambda o: None, without_holder), ["body"])
        without_reviewer = {key: value for key, value in CONTEXT.items() if key != "pre_reviewer"}
        self.kill("R-PRELIM/context-without-reviewer", self.mutate("R-PRELIM", lambda o: None, without_reviewer), ["body"])
        without_actors = dict(CONTEXT, actors={})
        self.kill("C-W/context-without-actor", self.mutate("C-W", lambda o: None, without_actors), ["audit-actor"])
        without_pin = dict(CONTEXT, engine_pin=None)
        self.kill("C-W/context-without-pin", self.mutate("C-W", lambda o: None, without_pin), ["audit-engine"])

    def test_10_pairing_and_run_completeness(self):
        def lines_of(test, records):
            return {line["id"]: line["problems"] for line in u5.evaluate(test, records, CONTEXT)}

        for test, rows in TABLE.items():
            controls = [row[0] for row in rows if row[1] == "control"]
            for control in controls:
                dependents = [row[0] for row in rows if row[3] == control]
                records = [canonical(row[0]) for row in rows if row[0] != control]
                got = lines_of(test, records)
                self.kill("%s/%s-missing" % (test, control), got[control], ["missing-case"])
                for case_id in dependents:
                    self.kill("%s/%s-unpaired-without-%s" % (test, case_id, control), got[case_id], ["unpaired"])
                records = [canonical(row[0]) for row in rows]
                records[[row[0] for row in rows].index(control)]["status"] = 500
                got = lines_of(test, records)
                self.kill("%s/%s-failed" % (test, control), got[control], ["status"])
                for case_id in dependents:
                    self.kill("%s/%s-unpaired-by-failed-%s" % (test, case_id, control), got[case_id], ["unpaired"])
                got = u5.evaluate(test, [canonical(row[0]) for row in rows] + [canonical(control)], CONTEXT)
                for line in got:
                    if line["id"] == control:
                        self.kill("%s/%s-duplicated" % (test, control), line["problems"], ["duplicate-case"])
                    elif line["id"] in dependents:
                        self.kill("%s/%s-unpaired-by-duplicated-%s" % (test, line["id"], control),
                                  line["problems"], ["unpaired"])
            got = u5.evaluate(test, [canonical(row[0]) for row in rows] + [canonical(rows[0][0])], CONTEXT)
            self.kill("%s/%s-duplicated" % (test, rows[0][0]), [line["problems"] for line in got
                                                               if line["id"] == rows[0][0]][0], ["duplicate-case"])
            self.assertEqual({line["id"]: line["problems"] for line in u5.evaluate(test, [], CONTEXT)},
                             {row[0]: ["missing-case"] for row in rows})
        foreign = lines_of("T1", [canonical(case_id) for case_id in u5.case_ids("T1")] + [canonical("C-A")])
        self.kill("T1/foreign-case", foreign["C-A"], ["unknown-case"])
        self.kill("T1/unknown-id", lines_of("T1", [canonical(case_id) for case_id in u5.case_ids("T1")]
                                            + [dict(canonical("C-W"), id="R-XYZ")])["R-XYZ"], ["unknown-case"])

    def test_11_precondition_is_fail_closed(self):
        self.assertEqual(u5.precondition("T1", self.capability(), PIN, u5.wav())["problems"], [])
        mutants = [
            ("available-true", self.capability(available=True), PIN, u5.wav()),
            ("available-missing", {k: v for k, v in self.capability().items() if k != "available"}, PIN, u5.wav()),
            ("available-text", self.capability(available="false"), PIN, u5.wav()),
            ("max-bytes-raised", self.capability(maxBytes=1048577), PIN, u5.wav()),
            ("max-bytes-text", self.capability(maxBytes="1048576"), PIN, u5.wav()),
            ("engine-pin-drift", self.capability(enginePin="whisper.cpp@0000000"), PIN, u5.wav()),
            ("source-pin-unread", self.capability(), None, u5.wav()),
            ("wav-drift", self.capability(), PIN, u5.wav(44100)),
            ("no-capability", None, PIN, u5.wav()),
        ]
        for name, capability, pin, wave in mutants:
            self.kill("precondition/" + name, u5.precondition("T1", capability, pin, wave)["problems"], ["precondition"])
        text = source("api/src/asr.service.ts")
        line = "export const ASR_ENGINE_PIN = '%s';" % PIN
        self.assertEqual(u5.source_engine_pin(text.replace("\n", "\r\n")), PIN)
        self.assertIsNone(u5.source_engine_pin(text.replace(line, line + "\n" + line)))
        self.assertIsNone(u5.source_engine_pin(text.replace(line, "")))

    def test_12_summary_is_complete_only_for_the_whole_battery(self):
        lines = [line for test in TABLE for line in u5.evaluate(test, [canonical(c) for c in u5.case_ids(test)], CONTEXT)]
        good = [u5.precondition(test, self.capability(), PIN, u5.wav()) for test in TABLE]
        self.assertTrue(u5.summary(lines, good)["complete"])
        broken = [
            ("case-missing", lines[1:], good),
            ("case-duplicated", lines + lines[:1], good),
            ("case-problem", [dict(lines[0], problems=["status"])] + lines[1:], good),
            ("precondition-missing", lines, good[1:]),
            ("precondition-failed", lines, [dict(good[0], problems=["precondition"])] + good[1:]),
        ]
        for name, some_lines, some_preconditions in broken:
            complete = u5.summary(some_lines, some_preconditions)["complete"]
            self.kill("summary/" + name, [] if complete else ["incomplete"], ["incomplete"], order=("incomplete",))

    def test_13_printed_lines_carry_no_body_secret_or_identity(self):
        leaked = canonical("R-PRELIM")
        leaked.update(body=nest(403, "Forbidden", SECRET), text=SECRET)
        leaked["after"]["audit"].append(dict(stray_row("R-PRELIM"), action="<b>" + SECRET))
        hostile = dict(canonical("C-W"), id="<script>", body={"code": "not a code " + SECRET})
        lines = u5.evaluate("T4", [leaked, canonical("C-P-AUTHOR"), canonical("C-P-REVIEWER")], CONTEXT)
        strange = u5.evaluate("T1", [hostile], CONTEXT)
        for line in lines + strange:
            self.assertEqual(set(line), u5.LINE_KEYS)
            printed = json.dumps(line, ensure_ascii=False)
            for forbidden in [SECRET, UID, PROBE, "판독", "<script>", "<b>"] + list(ACTORS.values()):
                self.assertNotIn(forbidden, printed)
        self.assertEqual((lines[0]["id"], lines[0]["secret_in_body"]), ("R-PRELIM", True))
        self.assertEqual((strange[0]["id"], strange[0]["code"], strange[0]["problems"]), ("?", None, ["unknown-case"]))

    def test_14_oracle_is_stdlib_only_and_never_loads_invariants_live(self):
        allowed = {"__future__", "ast", "hashlib", "json", "re", "struct", "collections", "dataclasses", "typing"}
        for relative, extra in (("tests/dictation_refusal_oracle.py", set()),
                                ("tests/dictation_refusal_oracle_test.py", {"copy", "pathlib", "sys", "unittest",
                                                                            "dictation_refusal_oracle"})):
            tree = ast.parse(source(relative))
            roots = {alias.name.split(".")[0] for node in ast.walk(tree) if isinstance(node, ast.Import)
                     for alias in node.names}
            roots |= {node.module.split(".")[0] for node in ast.walk(tree) if isinstance(node, ast.ImportFrom)}
            self.assertLessEqual(roots, allowed | extra, relative)
            self.assertNotIn("invariants_live", roots)
        self.assertNotIn("invariants_live", sys.modules)

    def test_15_live_battery_wiring_is_pinned(self):
        live = source("tests/invariants_live.py")
        self.assertEqual(u5.live_wiring_problems(live), [])
        tree = ast.parse(live)
        declared = sum(1 for cls in tree.body if isinstance(cls, ast.ClassDef)
                       and any(ast.unparse(base) == "unittest.TestCase" for base in cls.bases)
                       for node in cls.body if isinstance(node, ast.FunctionDef) and node.name.startswith("test"))
        print("U5-STATIC " + json.dumps({"declared_live_tests": declared}), flush=True)
        mutants = [
            ("backdate-removed", "                self.backdate_hold(uid, 6)\n", "                pass\n", ["wiring-A4"]),
            ("backdate-twice", "                self.backdate_hold(uid, 6)\n",
             "                self.backdate_hold(uid, 6)\n                self.backdate_hold(uid, 6)\n", ["wiring-A4"]),
            # test_member_suspension_... has the same login line; anchor on T7's own preceding lines.
            ("login-password-literal", 'logged_out: HttpResult | None = None\n            try:\n'
             '                opener, _sid = self.bff_login("doctor", self.stack.passwords["doctor"])',
             'logged_out: HttpResult | None = None\n            try:\n'
             '                opener, _sid = self.bff_login("doctor", "doctor")', ["wiring-A5"]),
            ("health-witness", 'self.assert_status(self.stack.request("GET", "/bootstrap", "tech"), 200)\n'
             '            finally:\n                lines = u5_emit("T1"',
             'self.assert_status(self.stack.request("GET", "/health", "tech"), 200)\n'
             '            finally:\n                lines = u5_emit("T1"', ["wiring-A3"]),
            ("second-select", '    rows = psql(\n        "SELECT jsonb_build_object("',
             '    psql("SELECT 1;")\n    rows = psql(\n        "SELECT jsonb_build_object("', ["wiring-A1"]),
            ("third-snapshot", '    after = u5_snapshot(uid, before["audit_max"])\n',
             '    after = u5_snapshot(uid, before["audit_max"])\n    u5_snapshot(uid, None)\n', ["wiring-A1"]),
            ("case-swapped", 'u5_call(records, "R-ROLE-CT"', 'u5_call(records, "R-ROLE"', ["wiring-cases"]),
            ("control-skipped", 'u5_call(records, "C-W2"', 'print(records, "C-W2"', ["wiring-cases"]),
            ("emit-key", 'lines = u5_emit("T2", records, context)', 'lines = u5_emit("T1", records, context)',
             ["wiring-keys"]),
            ("precondition-key", 'pin = u5_precondition(self, self.stack, "T8")',
             'pin = u5_precondition(self, self.stack, "T1")', ["wiring-keys"]),
            ("test-renamed", "def test_dictation_u5_08_approved_report_parity(",
             "def test_dictation_u5_08_approved_parity(", ["wiring-names"]),
            ("probe-left", "                    self.stack.cleanup_fixture(probe)\n", "                    pass\n",
             ["wiring-probe"]),
            ("summary-dropped", '"U5-SUMMARY "', '"U5-SUMMARY:"', ["wiring-summary"]),
            ("oracle-aliased", "import dictation_refusal_oracle as u5\n",
             "import dictation_refusal_oracle as oracle\nu5 = oracle\n", ["wiring-import"]),
        ]
        for name, old, new, expected in mutants:
            self.assertEqual(live.count(old), 1, name)
            self.kill("wiring/" + name, u5.live_wiring_problems(live.replace(old, new)), expected, order=u5.WIRING_TAGS)


def tearDownModule():
    killed = [name for name, expected, observed in MUTANTS if expected and observed == expected]
    print("U5-ORACLE " + json.dumps({"vectors": len(VECTORS), "mutants": len(MUTANTS), "killed": len(killed),
                                      "not_killed": sorted(set(name for name, _, _ in MUTANTS) - set(killed))}), flush=True)


if __name__ == "__main__":
    unittest.main(verbosity=2)
