# coding: utf-8
"""S9-U0a-PRE browser harness for temporary split pages (test side only; the product tree is never written).

Small pieces that the first move part can reuse:

* ``build(count, out_dir)`` / ``ScratchPages`` - temporary 18/30/45-part (or unsplit, count 0) copies of the page
  under test, generated by main_split_harness.cjs from tests/main_move_spec.json and checked with the move
  contract (same statements, bytes and outer markup). Each copy comes with a manifest that maps every top-level
  statement to its module and its line range in the served layout.
* ``Delivery`` - a Playwright route that serves one layout's scripts and decides when each answer arrives:
  every split boundary may be delayed (0 ms / 150 ms after the previous script), and one script may be held
  until ``release()``. Answers are only delivered from ``pump()``/route callbacks, so cases drive time through
  ``Delivery.wait()``.
* ``TRACE_SCRIPT`` - an init script that records, before any page script runs, every listener registration
  (addEventListener/removeEventListener and on* handler properties) with its target, type, options, listener
  source hash and the page frames that registered it, every dispatch to a recorded listener with its outcome,
  every script that finished executing, and uncaught errors. Listeners are called unchanged and nothing is
  caught: an exception leaves the listener as before (same error, same reported location) and the window's error
  report that follows is attached to that dispatch.
* ``derive_spec(page, out)`` - the move spec's runs for a page that changed since the move baseline.
* ``fixture_blocks(page, ranges)`` - the TypeScript-AST fixture projection for tests that compile part of the page's
  script: runs of the f1d5406 statements, named by their first and end declarations, taken from the page wherever
  they now sit (``REPORT_FIXTURE`` is the pair the report harness tests use).

What a case asserts is browser-observed behaviour (registrations, dispatch outcomes, what the screen shows), never
implementation strings (AGENTS 1-B). Statement names appear only in the manifest, to tell a reader where a
registration came from.
"""
import json
import shutil
import subprocess
import tempfile
import time
from pathlib import Path
from urllib.parse import urlparse

try:
    from playwright.sync_api import Error as PlaywrightError
except ImportError:  # fixture_blocks() serves stdlib-only mutant drivers too; Delivery needs Playwright
    PlaywrightError = None

ROOT = Path(__file__).resolve().parents[1]
PRODUCT_DIR = ROOT / "worklist-v0" / "hpacs-lite"
_HELPER = Path(__file__).with_name("main_split_harness.cjs")
TYPES = {".html": "text/html; charset=utf-8", ".js": "text/javascript; charset=utf-8"}
# TRACE_SCRIPT passes every console.error call of page code on with this first argument (browser notices lack it).
CONSOLE_MARK = "[kin-page-console]"


def build(count, out_dir, page=None, spec=None):
    """Write the `count`-part layout of `page` (default: the product main.html) into `out_dir`; return its manifest."""
    args = ["node", str(_HELPER), "split", str(count), str(out_dir)]
    if page or spec:
        args.append(str(page or PRODUCT_DIR / "main.html"))
    if spec:
        args.append(str(spec))
    return json.loads(subprocess.check_output(args, text=True, encoding="utf-8", cwd=ROOT))


# The two script runs the report harness tests compile (report_citation/cursor_insert/dictation_host/dictation_input/
# rebase/structure DOM tests and their mutant drivers; main_split_harness.cjs REPORT_FIXTURE is the same pair): what
# they used to cut between "let selectionSeq = 0;" .. "function reportSource()" and "function reportSource() {" ..
# "function heldByOther(s)".
REPORT_FIXTURE = {"BASE_BLOCK": ("selectionSeq", "reportSource"), "REPORT_BLOCK": ("reportSource", "heldByOther")}


def fixture_blocks(page, ranges):
    """Runs of the f1d5406 page's statements, named by the declarations that start and end them, taken from page
    wherever they now sit (main_split_harness.cjs fixtureBlocks): {key: (first, end)} -> {key: script text}."""
    return json.loads(subprocess.check_output(["node", str(_HELPER), "fixture", str(page), json.dumps(ranges)], text=True,
                                              encoding="utf-8", cwd=ROOT))


_FIXTURES = {}


def fixture_block(page, ranges, key):
    """One run of fixture_blocks(page, ranges), computed on first use and kept for the process. The projection runs
    node with the api TypeScript, which a job that only imports a suite (e.g. a selection check that imports
    test_dictation_live -> the capture and host suites) does not install: a suite asks for its runs where it builds its
    page, never at import."""
    cache = (str(page), json.dumps(ranges, sort_keys=True))
    if cache not in _FIXTURES:
        _FIXTURES[cache] = fixture_blocks(page, ranges)
    return _FIXTURES[cache][key]


def derive_spec(page, out):
    """The move spec's runs for `page` when it changed since the move baseline (written to `out`, a scratch path)."""
    return json.loads(subprocess.check_output(["node", str(_HELPER), "derive", str(page), str(out)], text=True,
                                              encoding="utf-8", cwd=ROOT))


class ScratchPages:
    """Temporary layouts in the OS temp directory, removed on close. ``layout(count)`` builds on first use.
    With `root` (a directory inside another ScratchPages' root) the owner of that root removes it."""

    def __init__(self, page=None, spec=None, prefix="kin-pre-split-", root=None):
        self.page, self.spec = page, spec
        self.owned = root is None
        self.root = Path(tempfile.mkdtemp(prefix=prefix)).resolve() if root is None else Path(root).resolve()
        self.root.mkdir(parents=True, exist_ok=True)
        self.layouts = {}

    def layout(self, count):
        if count not in self.layouts:
            directory = self.root / f"parts-{count}"
            self.layouts[count] = (directory, build(count, directory, self.page, self.spec))
        return self.layouts[count]

    def close(self):
        temp = Path(tempfile.gettempdir()).resolve()
        if self.owned and self.root.parent == temp and self.root.name.startswith("kin-pre-split-"):
            shutil.rmtree(self.root, ignore_errors=True)


def locate(manifest, file, line):
    """The statement of a served layout that holds (file, line), or None for a file outside the page script."""
    for statement in manifest["statements"]:
        if statement["file"] == file and statement["start"] <= line <= statement["end"]:
            return statement
    return None


def part_of(manifest, module):
    """The part file that holds `module`, or None when the module is in the layout's remaining inline script."""
    return manifest["parts"][module] if module < len(manifest["parts"]) else None


class Delivery:
    """Serves one layout (main.html, its parts and the page's other scripts) and times every script answer.

    ``delay_ms`` is added at each split boundary: a part is answered no earlier than ``delay_ms`` after the script
    before it was answered. ``hold`` names one script (a part, or one of the page's own scripts) whose answer waits
    for ``release()``. Anything else under the page directory falls back to the routes registered before this one.
    """

    def __init__(self, directory, manifest, base, delay_ms=0, hold=None, others=None, cache_headers=True):
        self.dir, self.manifest, self.base = Path(directory), manifest, base
        # no-store keeps every run's answers its own; without it (cache_headers=False) the page is answered as the
        # product's /worklist/ location answers it - no cache header - which a native back/forward cache needs.
        self.headers = {"Cache-Control": "no-store"} if cache_headers else {}
        # The page's other scripts: the product files, or `others(name) -> bytes` (e.g. a baseline's git blobs).
        self.others = others or (lambda name: (PRODUCT_DIR / name).read_bytes())
        self.order = list(manifest["scripts"])
        self.parts = set(manifest["parts"])
        self.delay = delay_ms / 1000.0
        self.hold, self.holding = hold, hold is not None
        if hold is not None and hold not in self.order:
            raise ValueError(f"{hold} is not a script of this layout")
        self.pending, self.arrival, self.delivered = {}, {}, {}
        self.requests = []

    def install(self, context):
        context.route(lambda url: urlparse(url).path.startswith(self.base), self._handle)
        return self

    def body(self, name):
        if name == "main.html" or name in self.parts:
            return (self.dir / name).read_bytes()
        return self.others(name)

    def _handle(self, route, request):
        name = urlparse(request.url).path[len(self.base):]
        if name == "main.html":
            return self._fulfill(route, name)
        if name not in self.order:
            return route.fallback()
        self.requests.append((time.monotonic(), name))
        if name in self.delivered:  # a reload of the same document asks again: answer as the first time
            return self._fulfill(route, name)
        self.pending[name], self.arrival[name] = route, time.monotonic()
        self.pump()

    def _fulfill(self, route, name):
        try:
            route.fulfill(status=200, body=self.body(name), content_type=TYPES[Path(name).suffix],
                          headers=dict(self.headers))
        except PlaywrightError:
            pass  # the page has gone

    def pump(self):
        now = time.monotonic()
        for index, name in enumerate(self.order):
            if name in self.delivered or name not in self.pending:
                continue
            if self.holding and name == self.hold:
                continue
            if name in self.parts:
                previous = self.order[index - 1]
                if previous not in self.delivered:
                    continue
                if now < max(self.arrival[name], self.delivered[previous]) + self.delay:
                    continue
            self._fulfill(self.pending.pop(name), name)
            self.delivered[name] = now

    def release(self):
        self.holding = False
        self.pump()

    def dispose(self):
        """Answer nothing more: abort what is still waiting (before the context closes)."""
        self.holding = True
        for route in self.pending.values():
            try:
                route.abort()
            except PlaywrightError:
                pass
        self.pending.clear()

    def wait(self, page, predicate, what, timeout=15.0):
        """Drive deliveries until `predicate()` holds (a callable, or a JS expression evaluated in the page)."""
        deadline = time.monotonic() + timeout
        check = predicate if callable(predicate) else (lambda: page.evaluate(predicate))
        while True:
            self.pump()
            if check():
                return
            if time.monotonic() >= deadline:
                raise AssertionError(f"{what}: not observed within {timeout:.0f}s "
                                     f"(delivered {len(self.delivered)}/{len(self.order)}, pending {sorted(self.pending)})")
            page.wait_for_timeout(5)

    def blocked(self, page):
        """The parser waits for the held script: every script before it ran and its own request is waiting."""
        if self.hold is None or self.hold not in self.pending:
            return False
        index = self.order.index(self.hold)
        return index == 0 or page.evaluate("name => window.__kinTrace.executed.includes(name)", self.order[index - 1])


# The trace is installed before any page script (context.add_init_script). It keeps its own references to the
# original EventTarget methods, so its own listeners are not part of the trace.
#
# An object is named when it is CREATED, never when something is first registered on it (Astra fix-2 design §1):
#   * the page markup's elements: their order of insertion by the parser, <script> elements left out (a split copy only
#     adds script tags). A MutationObserver numbers them; the parser runs a microtask checkpoint before every script, so
#     a parsed element has its number before any script can touch it;
#   * what scripts create: the creating API is hooked and keeps the call frames (the creation site) and how many times
#     that site had created before (its occurrence). An HTML subtree (innerHTML, cloning) has one occurrence for the
#     operation and each new element its slot in document order; a controller's signal belongs to the controller; an
#     object a promise delivers (a permission status, a media stream) takes its occurrence when it is asked for;
#   * window, document and the browser's other single objects, by name.
# A target with none of these is `unresolved`; the comparison refuses it instead of inventing a name. The role (id,
# place in the document, kind) stays beside it for a reader and for the suite's selectors - never as identity.
TRACE_SCRIPT = r"""(() => {
  if (window.__kinTrace) return;
  const add = EventTarget.prototype.addEventListener, remove = EventTarget.prototype.removeEventListener;
  const registrations = [], dispatches = [], executed = [], errors = [], objects = [], unresolved = [], parsed = [];
  let seq = 0, thrown = null;
  const births = new WeakMap(), siteCounts = new Map();
  const NOISY = new Set(['mousemove', 'pointermove', 'pointerrawupdate', 'mouseover', 'mouseout', 'pointerover',
    'pointerout', 'mouseenter', 'mouseleave', 'pointerenter', 'pointerleave']);
  function pathOf(el) {
    const steps = [];
    for (let node = el; node && node.nodeType === 1 && steps.length < 12; node = node.parentElement) {
      if (node.id) { steps.unshift('#' + node.id); break; }
      const parent = node.parentElement;
      const index = parent ? [...parent.children].indexOf(node) + 1 : 0;
      steps.unshift(node.localName + (index ? ':nth-child(' + index + ')' : ''));
    }
    return steps.join('>');
  }
  function roleOf(target) {
    if (target === window) return 'window';
    if (target === document) return 'document';
    if (target instanceof Element) return target.id ? '#' + target.id : target.isConnected ? pathOf(target) : '<' + target.localName + '>';
    return (target && target.constructor && target.constructor.name) || 'EventTarget';
  }
  function hash(text) {
    let h = 0x811c9dc5;
    for (let i = 0; i < text.length; i++) { h ^= text.charCodeAt(i); h = Math.imul(h, 0x01000193) >>> 0; }
    return h.toString(16).padStart(8, '0');
  }
  function frames() {
    const limit = Error.stackTraceLimit; Error.stackTraceLimit = 80;
    const stack = String(new Error().stack || ''); Error.stackTraceLimit = limit;
    const out = [];
    for (const line of stack.split('\n').slice(1)) {
      const m = /((?:https?|file):\/\/[^\s()]+):(\d+):(\d+)\)?\s*$/.exec(line);
      if (m) out.push([m[1].replace(/[?#].*$/, '').replace(/^.*\//, ''), +m[2], +m[3]]);
    }
    return out;
  }
  function script() {
    const current = document.currentScript;
    return current ? (current.src ? current.src.replace(/[?#].*$/, '').replace(/^.*\//, '') : 'inline') : null;
  }
  // A listener's identity across layouts: its source text with line ends normalized (an external part file keeps the
  // checkout's CRLF while the HTML parser hands inline script text over with LF).
  const source = fn => Function.prototype.toString.call(fn).replace(/\r\n?/g, '\n');
  function listenerHash(listener) {
    if (typeof listener === 'function') return hash(source(listener));
    if (listener && typeof listener.handleEvent === 'function') return 'h' + hash(source(listener.handleEvent));
    return null;
  }

  // ── the creation ledger ──
  const siteOf = fr => fr.map(f => f.join(':')).join(' ');
  function occurrence(site) { const n = (siteCounts.get(site) || 0) + 1; siteCounts.set(site, n); return n; }
  function born(obj, record) { births.set(obj, record); objects.push(record); return record; }
  function create(obj, kind, api, fr, owner, slot, n) {
    if (!obj || (typeof obj !== 'object' && typeof obj !== 'function')) return null;
    if (births.has(obj)) return births.get(obj);
    return born(obj, { id: objects.length + 1, seq: ++seq, kind, api, frames: fr,
      occurrence: n ?? occurrence(kind + '|' + api + '|' + siteOf(fr)),
      owner: owner && births.has(owner) ? births.get(owner).id : null, slot: slot ?? null });
  }
  const kindOf = node => 'element:' + node.localName;
  function subtree(root, api, fr, owner, includeRoot) {
    const n = occurrence('subtree|' + api + '|' + siteOf(fr));
    let slot = 0;
    const visit = node => { if (node.nodeType === 1 && !births.has(node)) create(node, kindOf(node), api, fr, owner, slot++, n); };
    if (includeRoot) visit(root);
    if (!root || typeof root.nodeType !== 'number') return;
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_ELEMENT);
    for (let node = walker.nextNode(); node; node = walker.nextNode()) visit(node);
  }
  const replace = (holder, name, wrap) => {
    const d = holder && Object.getOwnPropertyDescriptor(holder, name);
    if (d && typeof d.value === 'function') Object.defineProperty(holder, name, { ...d, value: wrap(d.value) });
  };
  const afterSet = (holder, name, after) => {
    const d = holder && Object.getOwnPropertyDescriptor(holder, name);
    if (!d || typeof d.set !== 'function') return;
    Object.defineProperty(holder, name, { ...d, set(value) {
      const fr = frames(), parent = this.parentNode, result = d.set.call(this, value);
      after(this, fr, parent); return result; } });
  };
  for (const name of ['createElement', 'createElementNS'])
    replace(Document.prototype, name, native => function (...args) {
      const fr = frames(), el = native.apply(this, args); create(el, kindOf(el), name, fr); return el; });
  replace(Node.prototype, 'cloneNode', native => function (...args) {
    const fr = frames(), copy = native.apply(this, args); subtree(copy, 'cloneNode', fr, this, true); return copy; });
  replace(Document.prototype, 'importNode', native => function (node, ...rest) {
    const fr = frames(), copy = native.call(this, node, ...rest); subtree(copy, 'importNode', fr, node, true); return copy; });
  afterSet(Element.prototype, 'innerHTML', (el, fr) => subtree(el, 'innerHTML', fr, el, false));
  afterSet(HTMLElement.prototype, 'innerText', (el, fr) => subtree(el, 'innerText', fr, el, false));
  afterSet(Element.prototype, 'outerHTML', (el, fr, parent) => parent && subtree(parent, 'outerHTML', fr, parent, false));
  replace(Element.prototype, 'insertAdjacentHTML', native => function (where, html) {
    const fr = frames(), parent = /^(beforebegin|afterend)$/i.test(where) ? this.parentNode : this;
    const result = native.call(this, where, html); if (parent) subtree(parent, 'insertAdjacentHTML', fr, this, false); return result; });
  replace(Range.prototype, 'createContextualFragment', native => function (html) {
    const fr = frames(), fragment = native.call(this, html); subtree(fragment, 'createContextualFragment', fr, null, false); return fragment; });
  replace(DOMParser.prototype, 'parseFromString', native => function (...args) {
    const fr = frames(), doc = native.apply(this, args); subtree(doc, 'parseFromString', fr, null, false); return doc; });
  const construct = (name, after) => {
    const Native = window[name], d = Object.getOwnPropertyDescriptor(window, name);
    if (typeof Native !== 'function' || !d || !(d.writable || d.configurable)) return;
    const proxy = new Proxy(Native, { construct(target, args, newTarget) {
      const fr = frames(), obj = Reflect.construct(target, args, newTarget === proxy ? target : newTarget);
      after(obj, fr); return obj; } });
    Object.defineProperty(window, name, { ...d, value: proxy });
  };
  for (const name of ['EventTarget', 'BroadcastChannel', 'XMLHttpRequest', 'WebSocket', 'EventSource', 'Worker',
    'SharedWorker', 'FileReader', 'Notification', 'MediaRecorder', 'MediaStream', 'AudioContext', 'OfflineAudioContext',
    'MediaSource', 'RTCPeerConnection', 'Image', 'Audio', 'Option'])
    construct(name, (obj, fr) => create(obj, obj instanceof Element ? kindOf(obj) : name, 'new ' + name, fr));
  construct('AudioWorkletNode', (node, fr) => {
    create(node, 'AudioWorkletNode', 'new AudioWorkletNode', fr);
    create(node.port, 'MessagePort', 'AudioWorkletNode.port', fr, node, 'port');
  });
  construct('MessageChannel', (channel, fr) => {
    create(channel, 'MessageChannel', 'new MessageChannel', fr);
    create(channel.port1, 'MessagePort', 'MessageChannel.port1', fr, channel, 'port1');
    create(channel.port2, 'MessagePort', 'MessageChannel.port2', fr, channel, 'port2');
  });
  construct('AbortController', (controller, fr) => {
    create(controller, 'AbortController', 'new AbortController', fr);
    create(controller.signal, 'AbortSignal', 'AbortController.signal', fr, controller, 'signal');
  });
  for (const name of ['timeout', 'any', 'abort'])
    replace(AbortSignal, name, native => function (...args) {
      const fr = frames(), signal = native.apply(this, args); create(signal, 'AbortSignal', 'AbortSignal.' + name, fr); return signal; });
  replace(window, 'matchMedia', native => function (...args) {
    const fr = frames(), list = native.apply(this, args); create(list, 'MediaQueryList', 'matchMedia', fr); return list; });
  replace(window, 'open', native => function (...args) {
    const fr = frames(), opened = native.apply(this, args); if (opened) create(opened, 'Window', 'window.open', fr); return opened; });
  const promised = (holder, name, kind, children) => replace(holder, name, native => function (...args) {
    const fr = frames(), n = occurrence(kind + '|' + name + '|' + siteOf(fr));
    return native.apply(this, args).then(value => {
      create(value, kind, name, fr, null, null, n); if (children) children(value, fr); return value; });
  });
  if (typeof Permissions === 'function') promised(Permissions.prototype, 'query', 'PermissionStatus');
  if (typeof MediaDevices === 'function') promised(MediaDevices.prototype, 'getUserMedia', 'MediaStream',
    (stream, fr) => stream.getTracks().forEach((track, i) => create(track, 'MediaStreamTrack', 'getUserMedia.track', fr, stream, i)));
  // The markup's elements, numbered in parser order (scripts aside); see above.
  const parsedNode = node => {
    if (node.nodeType !== 1 || births.has(node)) return;
    if (node.localName === 'script') { born(node, { id: objects.length + 1, seq: ++seq, kind: 'element:script', api: 'parser-script' }); return; }
    parsed.push(node.localName);
    born(node, { id: objects.length + 1, seq: ++seq, kind: kindOf(node), api: 'parser', parser: parsed.length });
  };
  new MutationObserver(records => {
    for (const r of records) for (const node of r.addedNodes) {
      parsedNode(node);
      if (node.nodeType !== 1) continue;
      const walker = document.createTreeWalker(node, NodeFilter.SHOW_ELEMENT);
      for (let n = walker.nextNode(); n; n = walker.nextNode()) parsedNode(n);
    }
  }).observe(document, { childList: true, subtree: true });
  let single = null;
  const singletons = () => single ??= [['window', () => window], ['document', () => document], ['screen', () => window.screen],
    ['visualViewport', () => window.visualViewport], ['screen.orientation', () => window.screen.orientation],
    ['mediaDevices', () => navigator.mediaDevices], ['fonts', () => document.fonts], ['performance', () => window.performance],
    ['serviceWorker', () => navigator.serviceWorker], ['speechSynthesis', () => window.speechSynthesis],
    ['connection', () => navigator.connection]].map(([name, get]) => { try { return [name, get()]; } catch (_) { return [name, null]; } })
    .filter(([, value]) => value);
  function objectOf(target) {
    const record = births.get(target);
    if (record) return 'o' + record.id;
    for (const [name, value] of singletons()) if (value === target) return 'singleton:' + name;
    unresolved.push({ seq: seq + 1, role: roleOf(target), kind: (target && target.constructor && target.constructor.name) || typeof target });
    return 'unresolved:' + unresolved.length;
  }

  // ── registrations and dispatches ──
  function record(kind, target, type, options, listener) {
    const capture = typeof options === 'boolean' ? options : !!(options && options.capture);
    const signal = options && typeof options === 'object' && options.signal ? options.signal : null;
    const entry = { seq: ++seq, kind, object: objectOf(target), target: roleOf(target), type: String(type), capture,
      once: !!(options && typeof options === 'object' && options.once),
      passive: options && typeof options === 'object' && 'passive' in options ? !!options.passive : null,
      signal: !!signal, signalObject: signal ? objectOf(signal) : null, listener: listenerHash(listener),
      script: script(), ready: document.readyState, frames: frames() };
    registrations.push(entry);
    return entry;
  }
  const wrappers = new WeakMap();
  function wrapperFor(target, type, capture, listener, entry) {
    if (!listener || (typeof listener !== 'function' && typeof listener !== 'object')) return listener;
    let byTarget = wrappers.get(listener);
    if (!byTarget) { byTarget = new WeakMap(); wrappers.set(listener, byTarget); }
    let byKey = byTarget.get(target);
    if (!byKey) { byKey = new Map(); byTarget.set(target, byKey); }
    const key = String(type) + '|' + capture;
    let wrapper = byKey.get(key);
    if (!wrapper && entry) {
      const registration = entry.seq, where = entry.target, object = entry.object;
      // No catch: an exception leaves the listener exactly as before (same error, same reported location); the
      // window error report that follows names it on this dispatch.
      wrapper = function (event) {
        const noisy = NOISY.has(event.type);
        const item = noisy ? null : { seq: ++seq, registration, target: where, object, type: event.type, trusted: event.isTrusted, error: null };
        if (item) dispatches.push(item);
        let completed = false;
        try {
          const result = typeof listener === 'function' ? listener.call(this, event) : listener.handleEvent(event);
          completed = true;
          return result;
        } finally {
          if (!completed && item) { item.error = 'threw'; thrown = item; }
        }
      };
      byKey.set(key, wrapper);
    }
    return wrapper || listener;
  }
  EventTarget.prototype.addEventListener = function (type, listener, options) {
    const entry = record('add', this, type, options, listener);
    const capture = typeof options === 'boolean' ? options : !!(options && options.capture);
    return add.call(this, type, wrapperFor(this, type, capture, listener, entry), options);
  };
  EventTarget.prototype.removeEventListener = function (type, listener, options) {
    record('remove', this, type, options, listener);
    const capture = typeof options === 'boolean' ? options : !!(options && options.capture);
    return remove.call(this, type, wrapperFor(this, type, capture, listener, null), options);
  };
  // on* handler properties: recorded (not wrapped), wherever the browser defines them.
  const holders = [window];
  for (const key of Object.getOwnPropertyNames(window)) {
    const d = Object.getOwnPropertyDescriptor(window, key);
    const value = d && d.value;
    if (typeof value === 'function' && value.prototype && (value === EventTarget || value.prototype instanceof EventTarget)) holders.push(value.prototype);
  }
  for (const holder of holders) for (const prop of Object.getOwnPropertyNames(holder)) {
    if (!prop.startsWith('on')) continue;
    const d = Object.getOwnPropertyDescriptor(holder, prop);
    if (!d || typeof d.set !== 'function' || !d.configurable) continue;
    Object.defineProperty(holder, prop, { configurable: true, enumerable: d.enumerable, get: d.get,
      set(value) { record(value ? 'property' : 'property-clear', this, prop.slice(2), false, value); return d.set.call(this, value); } });
  }
  add.call(document, 'load', event => {
    const el = event.target;
    if (el && el.localName === 'script' && el.src) executed.push(el.src.replace(/[?#].*$/, '').replace(/^.*\//, ''));
  }, true);
  add.call(window, 'error', event => {
    if (!(event instanceof ErrorEvent)) return; // a resource's load error, not an exception
    const error = event.error, message = error && error.name ? error.name + ': ' + error.message : String(event.message || 'error');
    errors.push({ seq: ++seq, message, file: String(event.filename || '').replace(/^.*\//, ''), line: event.lineno || 0,
      dispatch: thrown ? thrown.seq : null });
    if (thrown) { thrown.error = message; thrown = null; }
  }, true);
  // console.error calls of page code (a caught failure is reported that way, e.g. studyPriority's render): recorded,
  // and passed on with CONSOLE_MARK first so a reader of the browser console can tell them from browser notices.
  const consoleError = console.error;
  console.error = function (...args) {
    errors.push({ seq: ++seq, message: 'console.error: ' + args.map(String).join(' '),
      file: '', line: 0, dispatch: null });
    return consoleError.call(this, '[kin-page-console]', ...args);
  };
  add.call(window, 'unhandledrejection', event => {
    const reason = event.reason;
    errors.push({ seq: ++seq, message: 'unhandled rejection: ' + (reason && reason.message ? reason.name + ': ' + reason.message : String(reason)), file: '', line: 0 });
  });
  // The creation records an id names, with the records they belong to (a signal's controller, a clone's source).
  function objectsFor(ids) {
    const out = {}, todo = [...ids];
    while (todo.length) {
      const id = todo.pop();
      if (!id || !/^o\d+$/.test(id) || out[id]) continue;
      const record = objects[+id.slice(1) - 1];
      out[id] = record;
      if (record && record.owner) todo.push('o' + record.owner);
    }
    return out;
  }
  Object.defineProperty(window, '__kinTrace', { value: Object.freeze({ registrations, dispatches, executed, errors,
    unresolved, objectsFor, parsed: () => parsed.slice(), created: () => objects.length,
    mark(label) { const item = { seq: ++seq, label: String(label) }; dispatches.push(item); return item.seq; },
    now: () => seq }) });
})();"""


class TraceInfraFailure(AssertionError):
    """The trace cannot name a target by its creation (a creating API the trace does not know): a harness failure, never
    a pass and never a kill."""


def snapshot(page, since=0):
    """The trace recorded so far (entries with seq > since), with the creation records its targets and signals name."""
    return page.evaluate("""since => { const t = window.__kinTrace;
      const pick = list => list.filter(item => item.seq > since);
      const registrations = pick(t.registrations), dispatches = pick(t.dispatches);
      const ids = [...registrations.flatMap(r => [r.object, r.signalObject]), ...dispatches.map(d => d.object)];
      return { registrations, dispatches, errors: pick(t.errors), executed: t.executed.slice(), now: t.now(),
               objects: t.objectsFor(ids), unresolved: t.unresolved.slice() }; }""", since)


def attribute(manifest, registration):
    """(innermost page frame, statement of the outermost page-script frame) of one registration."""
    frames = registration["frames"]
    inner = frames[0] if frames else None
    owner = None
    for file, line, _ in reversed(frames):
        found = locate(manifest, file, line)
        if found:
            owner = found
            break
    return inner, owner


def frozen_indexes(page):
    """For each top-level statement of `page`, its f1d5406 statement index (by declared names, else by text; -1 for
    none) - the AST provenance two layouts of different pages share."""
    return json.loads(subprocess.check_output(["node", str(_HELPER), "frozen-index", str(page)], text=True,
                                              encoding="utf-8", cwd=ROOT))


class Provenance:
    """Call frames of one served layout, mapped to what the ORIGINAL page and a page that moved declarations share: a
    frame in the page script becomes (its f1d5406 statement, the line within that statement, the column) - the moved
    statements kept their text, so a place inside one keeps its line offset and column - and a frame in another script
    stays (file, line, column)."""

    def __init__(self, manifest, frozen):
        self.manifest, self.frozen = manifest, frozen

    def frame(self, frame):
        file, line, column = frame
        found = locate(self.manifest, file, line)
        if found:
            return ("main", self.frozen[found["index"]], line - found["start"], column)
        return (file, line, column)

    def stack(self, frames):
        return tuple(self.frame(frame) for frame in frames)

    def key(self, trace, ident):
        """An object's identity from its creation record (see TRACE_SCRIPT)."""
        if ident is None:
            return None
        if ident.startswith("singleton:"):
            return ("singleton", ident.split(":", 1)[1])
        record = trace["objects"].get(ident) if ident.startswith("o") else None
        if record is None:
            raise TraceInfraFailure(f"TRACE INFRA: target {ident} has no creation record; unresolved: "
                                    f"{trace.get('unresolved', [])[:5]}")
        if record["api"] == "parser":
            return ("parsed", record["parser"], record["kind"])
        if record["api"] == "parser-script":
            raise TraceInfraFailure(f"TRACE INFRA: a script element is a target ({ident})")
        owner = self.key(trace, "o" + str(record["owner"])) if record.get("owner") else None
        return ("created", record["kind"], record["api"], self.stack(record["frames"]), record["occurrence"],
                record.get("slot"), owner)


def full_order(trace, provenance):
    """Every registration in the order it was made: kind, the target as one object (its creation), event, options, the
    signal as one object, listener and the mapped call stack that made it."""
    if trace.get("unresolved"):
        raise TraceInfraFailure(f"TRACE INFRA: {len(trace['unresolved'])} unresolved targets, e.g. {trace['unresolved'][:5]}")
    return [(r["kind"], provenance.key(trace, r["object"]), r["type"], r["capture"], r["once"], r["passive"],
             provenance.key(trace, r["signalObject"]), r["listener"], provenance.stack(r["frames"]))
            for r in trace["registrations"]]


def dispatch_order(trace, provenance, since=0):
    """Every dispatch to a recorded listener after `since`, in order, by the registration it reached (as full_order
    names it)."""
    order = {r["seq"]: item for r, item in zip(trace["registrations"], full_order(trace, provenance))}
    return [(d["type"], d["trusted"], bool(d["error"]), order.get(d["registration"])) for d in trace["dispatches"]
            if "registration" in d and d["seq"] > since]


def order_difference(expected, observed, limit=5):
    """The first places where two ordered lists differ (readable, unlike a list diff of hundreds of tuples)."""
    out = []
    for i in range(max(len(expected), len(observed))):
        a = expected[i] if i < len(expected) else None
        b = observed[i] if i < len(observed) else None
        if a != b:
            out.append({"at": i, "original": a, "observed": b})
            if len(out) >= limit:
                break
    return out


def keep(directory, name, value):
    """Write one raw record (before anything is asserted on it); a failed write is a failure of its own."""
    path = Path(directory) / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=1, default=str), encoding="utf-8")
    return path


# The page side of a run whose clock is paused (Astra fix-2 design §2): every fetch the page starts (its answer, its body
# being read), and every timer and animation frame it asks for (when due, fired, cancelled), so a phase can end only when
# nothing is in flight and say which scheduled work it leaves for later. Installed after the clock, so the timers it
# wraps are the paused clock's. `__synBodyHolds` (a Map path -> releases), when the case sets it, keeps the body of an
# answer to that path from the page until the case releases it.
LEDGER_SCRIPT = r"""(() => {
  if (window.__synLedger) return;
  const fetches = [], timers = new Map(), answers = new WeakMap();
  let count = 0;
  const realFetch = window.fetch;
  window.fetch = function (input, init) {
    let path = '', query = '';
    try { const url = new URL(typeof input === 'string' ? input : input.url, location.href); path = url.pathname; query = url.search; } catch (_) {}
    const entry = { n: ++count, method: String((init && init.method) || (input && input.method) || 'GET').toUpperCase(), path, query,
      at: Date.now(), state: 'pending', status: null, body: 'unread' };
    fetches.push(entry);
    return realFetch.apply(this, arguments).then(response => {
      entry.state = 'answered'; entry.status = response.status; answers.set(response, entry); return response;
    }, error => { entry.state = 'failed'; entry.error = String(error && error.name); throw error; });
  };
  for (const name of ['json', 'text', 'arrayBuffer', 'blob', 'formData']) {
    const read = Response.prototype[name];
    Response.prototype[name] = function () {
      const entry = answers.get(this), reading = read.call(this);
      if (!entry) return reading;
      const holds = window.__synBodyHolds, held = holds && holds.has(entry.path);
      const finish = promise => promise.then(value => { entry.body = 'read'; return value; }, error => { entry.body = 'failed'; throw error; });
      if (!held) { entry.body = 'reading'; return finish(reading); }
      entry.body = 'held';
      return new Promise((resolve, reject) => holds.get(entry.path).push(() => {
        entry.body = 'reading'; finish(reading).then(resolve, reject); }));
    };
  }
  const wrap = (name, interval, frame) => {
    const native = window[name];
    if (typeof native !== 'function') return;
    window[name] = function (callback, delay, ...rest) {
      const wait = frame ? 16 : Math.max(0, +delay || 0), record = { kind: name, at: Date.now(), delay: wait, fired: 0, done: false, cleared: false };
      const run = typeof callback === 'function' ? function () { record.fired++; if (!interval) record.done = true; return callback.apply(this, arguments); } : callback;
      const id = frame ? native.call(this, run) : native.call(this, run, delay, ...rest);
      record.id = name + ':' + id;
      timers.set(record.id, record);
      return id;
    };
  };
  const unwrap = (name, kind) => {
    const native = window[name];
    if (typeof native !== 'function') return;
    window[name] = function (id) { const record = timers.get(kind + ':' + id); if (record) record.cleared = true; return native.call(this, id); };
  };
  wrap('setTimeout', false, false); wrap('setInterval', true, false); wrap('requestAnimationFrame', false, true);
  unwrap('clearTimeout', 'setTimeout'); unwrap('clearInterval', 'setInterval'); unwrap('cancelAnimationFrame', 'requestAnimationFrame');
  const due = record => record.at + record.delay * (record.kind === 'setInterval' ? record.fired + 1 : 1);
  Object.defineProperty(window, '__synLedger', { value: Object.freeze({
    state() {
      const live = [...timers.values()].filter(t => !t.done && !t.cleared);
      return { now: Date.now(), fetches: fetches.map(f => ({ ...f })),
        inFlight: fetches.filter(f => f.state === 'pending' || f.body === 'reading').length,
        held: fetches.filter(f => f.body === 'held').map(f => f.path),
        timers: live.map(t => ({ kind: t.kind, delay: t.delay, due: due(t), fired: t.fired })),
        nextDue: live.length ? Math.min(...live.map(due)) : null };
    },
    release(path) { const list = window.__synBodyHolds && window.__synBodyHolds.get(path); const n = list ? list.length : 0; if (list) list.splice(0).forEach(go => go()); return n; },
  }) });
})();"""


def by_target_event(registrations, keys=None):
    """Per (target, type): the ordered registration identities (kind, capture, once, passive, listener hash)."""
    result = {}
    for item in registrations:
        key = (item["target"], item["type"])
        if keys is not None and key not in keys:
            continue
        result.setdefault(key, []).append((item["kind"], item["capture"], item["once"], item["passive"], item["listener"]))
    return result
