# coding: utf-8
"""S9-U0a-PRE browser harness for temporary split pages (test side only; the product tree is never written).

Small pieces that the first move part can reuse:

* ``build(count, out_dir)`` / ``ScratchPages`` - temporary 18/30/45-part (or unsplit, count 0) copies of the page
  under test, generated by main_split_harness.cjs from tests/main_move_spec.json and checked with the move
  contract (same statements, bytes and outer markup). Each copy comes with a manifest that maps every top-level
  statement to its module and its line range in the served layout.
* ``Delivery`` - a Playwright route that serves one layout's scripts and decides when each answer arrives:
  every split boundary may be delayed (0 ms / 150 ms after the previous script), and one script may be held
  until ``release()``. Answers are only delivered from ``pump()``/route callbacks, so cases drive time through
  ``Delivery.wait()``.
* ``TRACE_SCRIPT`` - an init script that records, before any page script runs, every listener registration
  (addEventListener/removeEventListener and on* handler properties) with its target, type, options, listener
  source hash and the page frames that registered it, every dispatch to a recorded listener with its outcome,
  every script that finished executing, and uncaught errors. Listeners are called unchanged and nothing is
  caught: an exception leaves the listener as before (same error, same reported location) and the window's error
  report that follows is attached to that dispatch.
* ``derive_spec(page, out)`` - the move spec's runs for a page that changed since the move baseline.
* ``fixture_blocks(page, ranges)`` - the TypeScript-AST fixture projection for tests that compile part of the page's
  script: runs of the f1d5406 statements, named by their first and end declarations, taken from the page wherever
  they now sit (``REPORT_FIXTURE`` is the pair the report harness tests use).

What a case asserts is browser-observed behaviour (registrations, dispatch outcomes, what the screen shows), never
implementation strings (AGENTS 1-B). Statement names appear only in the manifest, to tell a reader where a
registration came from.
"""
import json
import shutil
import subprocess
import tempfile
import time
from pathlib import Path
from urllib.parse import urlparse

try:
    from playwright.sync_api import Error as PlaywrightError
except ImportError:  # fixture_blocks() serves stdlib-only mutant drivers too; Delivery needs Playwright
    PlaywrightError = None

ROOT = Path(__file__).resolve().parents[1]
PRODUCT_DIR = ROOT / "worklist-v0" / "hpacs-lite"
_HELPER = Path(__file__).with_name("main_split_harness.cjs")
TYPES = {".html": "text/html; charset=utf-8", ".js": "text/javascript; charset=utf-8"}
# TRACE_SCRIPT passes every console.error call of page code on with this first argument (browser notices lack it).
CONSOLE_MARK = "[kin-page-console]"


def build(count, out_dir, page=None, spec=None):
    """Write the `count`-part layout of `page` (default: the product main.html) into `out_dir`; return its manifest."""
    args = ["node", str(_HELPER), "split", str(count), str(out_dir)]
    if page or spec:
        args.append(str(page or PRODUCT_DIR / "main.html"))
    if spec:
        args.append(str(spec))
    return json.loads(subprocess.check_output(args, text=True, encoding="utf-8", cwd=ROOT))


# The two script runs the report harness tests compile (report_citation/cursor_insert/dictation_host/dictation_input/
# rebase/structure DOM tests and their mutant drivers; main_split_harness.cjs REPORT_FIXTURE is the same pair): what
# they used to cut between "let selectionSeq = 0;" .. "function reportSource()" and "function reportSource() {" ..
# "function heldByOther(s)".
REPORT_FIXTURE = {"BASE_BLOCK": ("selectionSeq", "reportSource"), "REPORT_BLOCK": ("reportSource", "heldByOther")}


def fixture_blocks(page, ranges):
    """Runs of the f1d5406 page's statements, named by the declarations that start and end them, taken from page
    wherever they now sit (main_split_harness.cjs fixtureBlocks): {key: (first, end)} -> {key: script text}."""
    return json.loads(subprocess.check_output(["node", str(_HELPER), "fixture", str(page), json.dumps(ranges)], text=True,
                                              encoding="utf-8", cwd=ROOT))


_FIXTURES = {}


def fixture_block(page, ranges, key):
    """One run of fixture_blocks(page, ranges), computed on first use and kept for the process. The projection runs
    node with the api TypeScript, which a job that only imports a suite (e.g. a selection check that imports
    test_dictation_live -> the capture and host suites) does not install: a suite asks for its runs where it builds its
    page, never at import."""
    cache = (str(page), json.dumps(ranges, sort_keys=True))
    if cache not in _FIXTURES:
        _FIXTURES[cache] = fixture_blocks(page, ranges)
    return _FIXTURES[cache][key]


def derive_spec(page, out):
    """The move spec's runs for `page` when it changed since the move baseline (written to `out`, a scratch path)."""
    return json.loads(subprocess.check_output(["node", str(_HELPER), "derive", str(page), str(out)], text=True,
                                              encoding="utf-8", cwd=ROOT))


class ScratchPages:
    """Temporary layouts in the OS temp directory, removed on close. ``layout(count)`` builds on first use.
    With `root` (a directory inside another ScratchPages' root) the owner of that root removes it."""

    def __init__(self, page=None, spec=None, prefix="kin-pre-split-", root=None):
        self.page, self.spec = page, spec
        self.owned = root is None
        self.root = Path(tempfile.mkdtemp(prefix=prefix)).resolve() if root is None else Path(root).resolve()
        self.root.mkdir(parents=True, exist_ok=True)
        self.layouts = {}

    def layout(self, count):
        if count not in self.layouts:
            directory = self.root / f"parts-{count}"
            self.layouts[count] = (directory, build(count, directory, self.page, self.spec))
        return self.layouts[count]

    def close(self):
        temp = Path(tempfile.gettempdir()).resolve()
        if self.owned and self.root.parent == temp and self.root.name.startswith("kin-pre-split-"):
            shutil.rmtree(self.root, ignore_errors=True)


def locate(manifest, file, line):
    """The statement of a served layout that holds (file, line), or None for a file outside the page script."""
    for statement in manifest["statements"]:
        if statement["file"] == file and statement["start"] <= line <= statement["end"]:
            return statement
    return None


def part_of(manifest, module):
    """The part file that holds `module`, or None when the module is in the layout's remaining inline script."""
    return manifest["parts"][module] if module < len(manifest["parts"]) else None


class Delivery:
    """Serves one layout (main.html, its parts and the page's other scripts) and times every script answer.

    ``delay_ms`` is added at each split boundary: a part is answered no earlier than ``delay_ms`` after the script
    before it was answered. ``hold`` names one script (a part, or one of the page's own scripts) whose answer waits
    for ``release()``. Anything else under the page directory falls back to the routes registered before this one.
    """

    def __init__(self, directory, manifest, base, delay_ms=0, hold=None, others=None, cache_headers=True):
        self.dir, self.manifest, self.base = Path(directory), manifest, base
        # no-store keeps every run's answers its own; without it (cache_headers=False) the page is answered as the
        # product's /worklist/ location answers it - no cache header - which a native back/forward cache needs.
        self.headers = {"Cache-Control": "no-store"} if cache_headers else {}
        # The page's other scripts: the product files, or `others(name) -> bytes` (e.g. a baseline's git blobs).
        self.others = others or (lambda name: (PRODUCT_DIR / name).read_bytes())
        self.order = list(manifest["scripts"])
        self.parts = set(manifest["parts"])
        self.delay = delay_ms / 1000.0
        self.hold, self.holding = hold, hold is not None
        if hold is not None and hold not in self.order:
            raise ValueError(f"{hold} is not a script of this layout")
        self.pending, self.arrival, self.delivered = {}, {}, {}
        self.requests = []

    def install(self, context):
        context.route(lambda url: urlparse(url).path.startswith(self.base), self._handle)
        return self

    def body(self, name):
        if name == "main.html" or name in self.parts:
            return (self.dir / name).read_bytes()
        return self.others(name)

    def _handle(self, route, request):
        name = urlparse(request.url).path[len(self.base):]
        if name == "main.html":
            return self._fulfill(route, name)
        if name not in self.order:
            return route.fallback()
        self.requests.append((time.monotonic(), name))
        if name in self.delivered:  # a reload of the same document asks again: answer as the first time
            return self._fulfill(route, name)
        self.pending[name], self.arrival[name] = route, time.monotonic()
        self.pump()

    def _fulfill(self, route, name):
        try:
            route.fulfill(status=200, body=self.body(name), content_type=TYPES[Path(name).suffix],
                          headers=dict(self.headers))
        except PlaywrightError:
            pass  # the page has gone

    def pump(self):
        now = time.monotonic()
        for index, name in enumerate(self.order):
            if name in self.delivered or name not in self.pending:
                continue
            if self.holding and name == self.hold:
                continue
            if name in self.parts:
                previous = self.order[index - 1]
                if previous not in self.delivered:
                    continue
                if now < max(self.arrival[name], self.delivered[previous]) + self.delay:
                    continue
            self._fulfill(self.pending.pop(name), name)
            self.delivered[name] = now

    def release(self):
        self.holding = False
        self.pump()

    def dispose(self):
        """Answer nothing more: abort what is still waiting (before the context closes)."""
        self.holding = True
        for route in self.pending.values():
            try:
                route.abort()
            except PlaywrightError:
                pass
        self.pending.clear()

    def wait(self, page, predicate, what, timeout=15.0):
        """Drive deliveries until `predicate()` holds (a callable, or a JS expression evaluated in the page)."""
        deadline = time.monotonic() + timeout
        check = predicate if callable(predicate) else (lambda: page.evaluate(predicate))
        while True:
            self.pump()
            if check():
                return
            if time.monotonic() >= deadline:
                raise AssertionError(f"{what}: not observed within {timeout:.0f}s "
                                     f"(delivered {len(self.delivered)}/{len(self.order)}, pending {sorted(self.pending)})")
            page.wait_for_timeout(5)

    def blocked(self, page):
        """The parser waits for the held script: every script before it ran and its own request is waiting."""
        if self.hold is None or self.hold not in self.pending:
            return False
        index = self.order.index(self.hold)
        return index == 0 or page.evaluate("name => window.__kinTrace.executed.includes(name)", self.order[index - 1])


# The trace is installed before any page script (context.add_init_script). It keeps its own references to the
# original EventTarget methods, so its own listeners are not part of the trace.
TRACE_SCRIPT = r"""(() => {
  if (window.__kinTrace) return;
  const add = EventTarget.prototype.addEventListener, remove = EventTarget.prototype.removeEventListener;
  const registrations = [], dispatches = [], executed = [], errors = [];
  let seq = 0, thrown = null;
  // A target's identity is its role (id, or its place in the document, or its kind when detached) plus the order in
  // which objects of that role first appeared: a second, different element given the same id is '#id@2', never merged
  // with the first (Astra PRE-A03).
  const names = new WeakMap(), counters = new Map(), ordinals = new Map();
  const NOISY = new Set(['mousemove', 'pointermove', 'pointerrawupdate', 'mouseover', 'mouseout', 'pointerover',
    'pointerout', 'mouseenter', 'mouseleave', 'pointerenter', 'pointerleave']);
  function pathOf(el) {
    const steps = [];
    for (let node = el; node && node.nodeType === 1 && steps.length < 12; node = node.parentElement) {
      if (node.id) { steps.unshift('#' + node.id); break; }
      const parent = node.parentElement;
      const index = parent ? [...parent.children].indexOf(node) + 1 : 0;
      steps.unshift(node.localName + (index ? ':nth-child(' + index + ')' : ''));
    }
    return steps.join('>');
  }
  function nameOf(target) {
    if (target === window) return 'window';
    if (target === document) return 'document';
    let name = names.get(target);
    if (name) return name;
    if (target instanceof Element && (target.id || target.isConnected)) {
      const role = target.id ? '#' + target.id : pathOf(target);
      const n = (ordinals.get(role) || 0) + 1; ordinals.set(role, n);
      name = n === 1 ? role : role + '@' + n;
    } else {
      const kind = (target instanceof Element ? '<' + target.localName + '>' : (target && target.constructor && target.constructor.name)) || 'EventTarget';
      const n = (counters.get(kind) || 0) + 1; counters.set(kind, n);
      name = kind + '~' + n;
    }
    names.set(target, name);
    return name;
  }
  function hash(text) {
    let h = 0x811c9dc5;
    for (let i = 0; i < text.length; i++) { h ^= text.charCodeAt(i); h = Math.imul(h, 0x01000193) >>> 0; }
    return h.toString(16).padStart(8, '0');
  }
  function frames() {
    const limit = Error.stackTraceLimit; Error.stackTraceLimit = 80;
    const stack = String(new Error().stack || ''); Error.stackTraceLimit = limit;
    const out = [];
    for (const line of stack.split('\n').slice(1)) {
      const m = /((?:https?|file):\/\/[^\s()]+):(\d+):(\d+)\)?\s*$/.exec(line);
      if (m) out.push([m[1].replace(/[?#].*$/, '').replace(/^.*\//, ''), +m[2], +m[3]]);
    }
    return out;
  }
  function script() {
    const current = document.currentScript;
    return current ? (current.src ? current.src.replace(/[?#].*$/, '').replace(/^.*\//, '') : 'inline') : null;
  }
  // A listener's identity across layouts: its source text with line ends normalized (an external part file keeps the
  // checkout's CRLF while the HTML parser hands inline script text over with LF).
  const source = fn => Function.prototype.toString.call(fn).replace(/\r\n?/g, '\n');
  function listenerHash(listener) {
    if (typeof listener === 'function') return hash(source(listener));
    if (listener && typeof listener.handleEvent === 'function') return 'h' + hash(source(listener.handleEvent));
    return null;
  }
  function record(kind, target, type, options, listener) {
    const capture = typeof options === 'boolean' ? options : !!(options && options.capture);
    const entry = { seq: ++seq, kind, target: nameOf(target), type: String(type), capture,
      once: !!(options && typeof options === 'object' && options.once),
      passive: options && typeof options === 'object' && 'passive' in options ? !!options.passive : null,
      signal: !!(options && typeof options === 'object' && options.signal), listener: listenerHash(listener),
      script: script(), ready: document.readyState, frames: frames() };
    registrations.push(entry);
    return entry;
  }
  const wrappers = new WeakMap();
  function wrapperFor(target, type, capture, listener, entry) {
    if (!listener || (typeof listener !== 'function' && typeof listener !== 'object')) return listener;
    let byTarget = wrappers.get(listener);
    if (!byTarget) { byTarget = new WeakMap(); wrappers.set(listener, byTarget); }
    let byKey = byTarget.get(target);
    if (!byKey) { byKey = new Map(); byTarget.set(target, byKey); }
    const key = String(type) + '|' + capture;
    let wrapper = byKey.get(key);
    if (!wrapper && entry) {
      const registration = entry.seq, where = entry.target;
      // No catch: an exception leaves the listener exactly as before (same error, same reported location); the
      // window error report that follows names it on this dispatch.
      wrapper = function (event) {
        const noisy = NOISY.has(event.type);
        const item = noisy ? null : { seq: ++seq, registration, target: where, type: event.type, trusted: event.isTrusted, error: null };
        if (item) dispatches.push(item);
        let completed = false;
        try {
          const result = typeof listener === 'function' ? listener.call(this, event) : listener.handleEvent(event);
          completed = true;
          return result;
        } finally {
          if (!completed && item) { item.error = 'threw'; thrown = item; }
        }
      };
      byKey.set(key, wrapper);
    }
    return wrapper || listener;
  }
  EventTarget.prototype.addEventListener = function (type, listener, options) {
    const entry = record('add', this, type, options, listener);
    const capture = typeof options === 'boolean' ? options : !!(options && options.capture);
    return add.call(this, type, wrapperFor(this, type, capture, listener, entry), options);
  };
  EventTarget.prototype.removeEventListener = function (type, listener, options) {
    record('remove', this, type, options, listener);
    const capture = typeof options === 'boolean' ? options : !!(options && options.capture);
    return remove.call(this, type, wrapperFor(this, type, capture, listener, null), options);
  };
  // on* handler properties: recorded (not wrapped), wherever the browser defines them.
  const holders = [window];
  for (const key of Object.getOwnPropertyNames(window)) {
    const d = Object.getOwnPropertyDescriptor(window, key);
    const value = d && d.value;
    if (typeof value === 'function' && value.prototype && (value === EventTarget || value.prototype instanceof EventTarget)) holders.push(value.prototype);
  }
  for (const holder of holders) for (const prop of Object.getOwnPropertyNames(holder)) {
    if (!prop.startsWith('on')) continue;
    const d = Object.getOwnPropertyDescriptor(holder, prop);
    if (!d || typeof d.set !== 'function' || !d.configurable) continue;
    Object.defineProperty(holder, prop, { configurable: true, enumerable: d.enumerable, get: d.get,
      set(value) { record(value ? 'property' : 'property-clear', this, prop.slice(2), false, value); return d.set.call(this, value); } });
  }
  add.call(document, 'load', event => {
    const el = event.target;
    if (el && el.localName === 'script' && el.src) executed.push(el.src.replace(/[?#].*$/, '').replace(/^.*\//, ''));
  }, true);
  add.call(window, 'error', event => {
    if (!(event instanceof ErrorEvent)) return; // a resource's load error, not an exception
    const error = event.error, message = error && error.name ? error.name + ': ' + error.message : String(event.message || 'error');
    errors.push({ seq: ++seq, message, file: String(event.filename || '').replace(/^.*\//, ''), line: event.lineno || 0,
      dispatch: thrown ? thrown.seq : null });
    if (thrown) { thrown.error = message; thrown = null; }
  }, true);
  // console.error calls of page code (a caught failure is reported that way, e.g. studyPriority's render): recorded,
  // and passed on with CONSOLE_MARK first so a reader of the browser console can tell them from browser notices.
  const consoleError = console.error;
  console.error = function (...args) {
    errors.push({ seq: ++seq, message: 'console.error: ' + args.map(String).join(' '),
      file: '', line: 0, dispatch: null });
    return consoleError.call(this, '[kin-page-console]', ...args);
  };
  add.call(window, 'unhandledrejection', event => {
    const reason = event.reason;
    errors.push({ seq: ++seq, message: 'unhandled rejection: ' + (reason && reason.message ? reason.name + ': ' + reason.message : String(reason)), file: '', line: 0 });
  });
  Object.defineProperty(window, '__kinTrace', { value: Object.freeze({ registrations, dispatches, executed, errors,
    mark(label) { const item = { seq: ++seq, label: String(label) }; dispatches.push(item); return item.seq; },
    now: () => seq }) });
})();"""


def snapshot(page, since=0):
    """The trace recorded so far (entries with seq > since)."""
    return page.evaluate("""since => { const t = window.__kinTrace;
      const pick = list => list.filter(item => item.seq > since);
      return { registrations: pick(t.registrations), dispatches: pick(t.dispatches), errors: pick(t.errors),
               executed: t.executed.slice(), now: t.now() }; }""", since)


def attribute(manifest, registration):
    """(innermost page frame, statement of the outermost page-script frame) of one registration."""
    frames = registration["frames"]
    inner = frames[0] if frames else None
    owner = None
    for file, line, _ in reversed(frames):
        found = locate(manifest, file, line)
        if found:
            owner = found
            break
    return inner, owner


def frozen_indexes(page):
    """For each top-level statement of `page`, its f1d5406 statement index (by declared names, else by text; -1 for
    none) - the AST provenance two layouts of different pages share."""
    return json.loads(subprocess.check_output(["node", str(_HELPER), "frozen-index", str(page)], text=True,
                                              encoding="utf-8", cwd=ROOT))


def provenance(manifest, frozen, registration):
    """Where a registration was made, the same for the ORIGINAL page and a page that moved declarations: the f1d5406
    statement of its outermost page-script frame, else the outermost frame of another script (file, line)."""
    _, owner = attribute(manifest, registration)
    if owner:
        return ("statement", frozen[owner["index"]])
    frames = registration["frames"]
    return ("script", frames[-1][0], frames[-1][1]) if frames else None


def full_order(manifest, frozen, registrations):
    """Every registration in the order it was made: kind, target identity (role and creation order), event, options,
    listener and provenance."""
    return [(r["kind"], r["target"], r["type"], r["capture"], r["once"], r["passive"], r["signal"], r["listener"],
             provenance(manifest, frozen, r)) for r in registrations]


def order_difference(expected, observed, limit=5):
    """The first places where two ordered lists differ (readable, unlike a list diff of hundreds of tuples)."""
    out = []
    for i in range(max(len(expected), len(observed))):
        a = expected[i] if i < len(expected) else None
        b = observed[i] if i < len(observed) else None
        if a != b:
            out.append({"at": i, "original": a, "observed": b})
            if len(out) >= limit:
                break
    return out


def by_target_event(registrations, keys=None):
    """Per (target, type): the ordered registration identities (kind, capture, once, passive, listener hash)."""
    result = {}
    for item in registrations:
        key = (item["target"], item["type"])
        if keys is not None and key not in keys:
            continue
        result.setdefault(key, []).append((item["kind"], item["capture"], item["once"], item["passive"], item["listener"]))
    return result
