#!/usr/bin/env python3
"""A11-OUTPUT-1 volume-mip-output transport diagnostic harness (observation only; NEVER MERGE).

One manual, first-attempt, GitHub-hosted synthetic run of the baseline volume-mip-output job's own steps, selection, caps and
budgets, with added observation only: Chromium Default-mode NetLog and page-visible request failures recorded by a startup hook,
and a generated test-only nginx logging copy with an effective-configuration dump. Product code, tests, assertions, messages,
re-attempt guards, budgets and other profiles are the baseline's own: the checkout is the exact baseline commit while the profile
runs, and the observation files live outside it.

  plan       local: registry, scope, workflow, generated proxy copy and syntax checks; prints the harness file hashes
  generate   local: write the generated proxy files for review into --out
  restore    hosted: guard the dispatch and the harness, then check out the exact baseline tree
  prepare    hosted: write the generated proxy logging copy, the effective-configuration dump and the compose override
  preflight  hosted, before the stack: one browser launch through the hook shows NetLog capture works on this runner
  collect    hosted, always: copy and sanitize the observation files, guard the tree after the profile, run analyze.py
  cleanup    hosted, always: remove any container, volume or network left on the disposable runner, and the override
"""
import argparse
import datetime
import hashlib
import json
import os
import py_compile
import re
import subprocess
import sys
import tempfile
import traceback
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import analyze  # noqa: E402

HARNESS_DIR = 'diagnostic-harness/a11-output-transport'
WORKFLOW = '.github/workflows/validate.yml'
TEMPLATE = 'proxy/nginx.conf.template'
OVERRIDE = 'docker-compose.override.yml'
UPLOAD = 'tmp/mipout-diag'
PROFILE_OUT = 'tests/e2e/artifacts/volume-mip-output-ci'
DIAG_NAME = 'transport-diagnostics'
GIT_OVERRIDES = ('GIT_DIR', 'GIT_WORK_TREE', 'GIT_INDEX_FILE', 'GIT_OBJECT_DIRECTORY')
GITHUB = ('GITHUB_RUN_ID', 'GITHUB_RUN_ATTEMPT', 'GITHUB_JOB', 'GITHUB_SHA', 'GITHUB_REF', 'GITHUB_EVENT_NAME',
          'RUNNER_NAME', 'RUNNER_ENVIRONMENT', 'ImageVersion')

# The generated copy is the baseline template with exactly this block inserted before its first directive, in the http context of
# the image's conf.d include. It adds a second access log with connection fields and an info-level error log in a mounted
# directory, and repeats the image's main-level stderr error log so the profile's own services.log keeps its lines. No listener,
# keepalive, HTTP/2, timeout, buffer, upstream or location setting is added or changed.
ANCHOR = 'limit_req_zone $binary_remote_addr zone=kin_registration:10m rate=10r/m;\n'
LOGGING_BLOCK = (
    '# >>> kin transport diagnostic: generated test-only logging copy (never production, never committed)\n'
    "log_format kin_diag_conn 'msec=$msec pid=$pid conn=$connection conn_req=$connection_requests http2=$http2 '\n"
    "                         'proto=$server_protocol remote=$remote_addr:$remote_port server_port=$server_port '\n"
    "                         'method=$request_method uri=\"$uri\" status=$status bytes=$bytes_sent req_len=$request_length '\n"
    "                         'req_time=$request_time up_status=$upstream_status up_time=$upstream_response_time '\n"
    "                         'completion=$request_completion ua=\"$http_user_agent\"';\n"
    'access_log /var/log/kin-diag/access-conn.log kin_diag_conn;\n'
    'error_log /var/log/kin-diag/error-info.log info;\n'
    'error_log /var/log/nginx/error.log notice;\n'
    '# <<< kin transport diagnostic\n'
    '\n')
DUMP_SCRIPT = '''#!/bin/sh
# Generated by the never-merged A11 output transport diagnostic harness for one disposable hosted run only.
# After the image's own entrypoint scripts rendered the templates, append the effective configuration with the generated Orthanc
# Basic credential redacted, and keep the diagnostic logs readable by the runner. It changes no configuration and never fails
# container startup.
umask 022
dir=/var/log/kin-diag
for name in access-conn.log error-info.log nginx-effective-config.txt; do
  touch "$dir/$name" 2>/dev/null && chmod 0644 "$dir/$name" 2>/dev/null
done
{
  echo "### kin-diag effective configuration at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  nginx -V 2>&1
  nginx -T 2>&1
  echo "### nginx -T exit $?"
} | sed -E 's|(Basic )[A-Za-z0-9+/=]+|\\1[REDACTED]|g' >> "$dir/nginx-effective-config.txt" 2>/dev/null \\
  || echo "[kin-diag] effective configuration was not recorded" >&2
exit 0
'''
OVERRIDE_TEXT = '''# Generated by the never-merged A11 output transport diagnostic harness for one disposable hosted run only.
# Observation only: a logging copy of proxy/nginx.conf.template, an effective-configuration dump and a log directory.
services:
  proxy:
    volumes:
      - type: bind
        source: {template}
        target: /etc/nginx/templates/default.conf.template
        read_only: true
      - type: bind
        source: {script}
        target: /docker-entrypoint.d/99-kin-diag-effective-config.sh
        read_only: true
      - type: bind
        source: {logs}
        target: /var/log/kin-diag
'''

JWT = re.compile(r'eyJ[A-Za-z0-9_-]+(?:\.[A-Za-z0-9_-]+){2,4}')
AUTH = re.compile(r'(?i)\b(bearer|basic)\s+(?!\[REDACTED\])[A-Za-z0-9._~+/=-]+')
HEADER = re.compile(r'(?i)((?:set-cookie|cookie|proxy-authorization|authorization):)[ \t]*(?!\[REDACTED\])[^\r\n"]+')
FIELD = re.compile(r'(?i)("(?:access_token|refresh_token|id_token|temporaryPassword|password|client_secret|cookie|authorization)"\s*:\s*)"(?!\[REDACTED\]")[^"\r\n]*"')
QUERY = re.compile(r'((?:https?://[^\s"\'<>?#]+)|(?:/[^\s"\'<>?#]*))\?([^\s"\'<>#]*)')


class GuardFailure(Exception):
    pass


def git(*args, cwd=None, codes=(0,), data=None):
    done = subprocess.run(['git', '-c', 'core.autocrlf=false', *args], cwd=cwd, input=data, capture_output=True)
    if done.returncode not in codes:
        raise GuardFailure('git %s exited %d: %s' % (' '.join(args), done.returncode, done.stderr.decode('utf-8', 'replace').strip()))
    return done


def out(*args, cwd=None):
    return git(*args, cwd=cwd).stdout.decode('utf-8').rstrip('\n')


def blob(rev, path):
    return git('cat-file', 'blob', '%s:%s' % (rev, path)).stdout


def sha256(data):
    return hashlib.sha256(data).hexdigest()


def blob_id(data):
    return hashlib.sha1(b'blob %d\0' % len(data) + data).hexdigest()


def now():
    return datetime.datetime.now(datetime.timezone.utc).isoformat()


def registry():
    return json.loads((HERE / 'preregistration.json').read_text(encoding='utf-8'))


class Record:
    """One JSON evidence file per harness step, written even when a check fails."""

    def __init__(self, kind):
        self.data = {'kind': kind, 'started_utc': now(), 'ended_utc': None, 'result': 'running',
                     'github': {k: os.environ.get(k) for k in GITHUB}, 'checks': []}

    def check(self, name, expected, actual):
        ok = expected == actual
        self.data['checks'].append({'name': name, 'ok': ok, 'expected': expected, 'actual': actual})
        if not ok:
            raise GuardFailure('%s: expected %r, actual %r' % (name, expected, actual))

    def run(self, work, path=None):
        try:
            work()
            self.data['result'] = 'passed'
        except BaseException as error:
            self.data.update(result='failed', error='%s: %s' % (type(error).__name__, error))
            raise
        finally:
            self.data['ended_utc'] = now()
            text = json.dumps(self.data, ensure_ascii=False, indent=1, default=str) + '\n'
            if path is None:
                sys.stdout.buffer.write(text.encode('utf-8'))
                sys.stdout.flush()
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(text.encode('utf-8'))


def result_of(path):
    try:
        return json.loads(path.read_text(encoding='utf-8')).get('result')
    except (OSError, ValueError):
        return None


def diag_root():
    temp = os.environ.get('RUNNER_TEMP')
    if not temp or not Path(temp).is_absolute():
        raise GuardFailure('hosted harness steps need an absolute RUNNER_TEMP')
    return Path(temp) / DIAG_NAME


def allowed(path):
    return path == WORKFLOW or path.startswith(HARNESS_DIR + '/')


def untracked():
    rows = [r[3:] for r in out('status', '--porcelain=v1', '--untracked-files=normal').splitlines() if r.startswith('?? ')]
    return {'count': len(rows), 'first': rows[:20]}


# ------------------------------------------------------------------------------------------------------ guards and scope
def hosted(rec, reg):
    rec.check('GitHub Actions', 'true', os.environ.get('GITHUB_ACTIONS'))
    rec.check('GitHub-hosted runner', 'github-hosted', os.environ.get('RUNNER_ENVIRONMENT'))
    rec.check('dispatched by hand', 'workflow_dispatch', os.environ.get('GITHUB_EVENT_NAME'))
    rec.check('harness branch', reg['harness_ref'], os.environ.get('GITHUB_REF'))
    rec.check('first attempt only, no rerun', '1', os.environ.get('GITHUB_RUN_ATTEMPT'))
    rec.check('dispatch input harness_sha is the dispatched commit', os.environ.get('GITHUB_SHA'), os.environ.get('EXPECTED_HARNESS_SHA'))
    rec.check('dispatch input baseline_sha is the registered baseline', reg['baseline']['sha'], os.environ.get('EXPECTED_BASELINE_SHA'))
    rec.check('commands run from the product checkout root', str(Path.cwd().resolve()), str(Path(out('rev-parse', '--show-toplevel')).resolve()))


def local_only(rec):
    rec.check('plan runs locally, never in Actions', None, os.environ.get('GITHUB_ACTIONS'))
    for name in GIT_OVERRIDES:
        rec.check('no %s override' % name, None, os.environ.get(name))


def harness_files():
    return sorted(p for p in HERE.rglob('*') if p.is_file() and '__pycache__' not in p.parts)


def check_staged(rec):
    names = out('ls-tree', '-r', '--name-only', 'HEAD', HARNESS_DIR).splitlines()
    for name in names:
        rec.check('harness file %s equals its HEAD blob' % name, sha256(blob('HEAD', name)),
                  sha256((HERE / Path(name).relative_to(HARNESS_DIR)).read_bytes()))
    rec.check('no harness file outside HEAD', sorted(Path(n).relative_to(HARNESS_DIR).as_posix() for n in names),
              [p.relative_to(HERE).as_posix() for p in harness_files()])


def check_scope(rec, reg):
    base = reg['baseline']['sha']
    rec.check('baseline is an ancestor of the harness commit', 0, git('merge-base', '--is-ancestor', base, 'HEAD', codes=(0, 1)).returncode)
    changed = out('diff', '--name-only', '--no-renames', base, 'HEAD').splitlines()
    rec.check('harness commits change only the harness workflow and the harness directory', [], [p for p in changed if not allowed(p)])
    rec.data['harness_changed_paths'] = changed


def check_registry(rec, reg):
    base = reg['baseline']
    rec.check('baseline commit', base['sha'], out('rev-parse', base['sha'] + '^{commit}'))
    rec.check('baseline tree', base['tree'], out('rev-parse', base['sha'] + '^{tree}'))
    rec.check('baseline tree equals the reviewed candidate tree', base['tree'], out('rev-parse', base['candidate_sha'] + '^{tree}'))
    for key, path in (('workflow_blob', WORKFLOW), ('proxy_template_blob', TEMPLATE), ('compose_blob', 'docker-compose.yml')):
        rec.check('baseline %s' % path, base[key], out('rev-parse', '%s:%s' % (base['sha'], path)))
    rec.check('registered baseline source hashes', base['source_sha256'],
              {path: sha256(blob(base['sha'], path)) for path in sorted(base['source_sha256'])})


def job_blocks(text):
    rows = text.split('\n')
    blocks, name = {}, None
    for line in rows[rows.index('jobs:') + 1:]:
        match = re.match(r'^  ([A-Za-z0-9_-]+):$', line)
        if match:
            name = match.group(1)
            blocks[name] = []
        elif name is not None:
            blocks[name].append(line)
    return blocks


def split_job(block):
    header, steps = [], []
    for line in block:
        if line.startswith('      - '):
            steps.append([line])
        elif steps:
            steps[-1].append(line)
        elif line.strip() and not line.strip().startswith('#'):
            header.append(line)
    return header, ['\n'.join(step).rstrip() for step in steps]


def step_name(step):
    match = re.search(r'^      (?:- |  )name: (.*)$', step, re.M)
    return match.group(1) if match else None


def check_workflow(rec, reg, text, original):
    job = reg['native_job']
    rec.check('harness workflow has no automatic trigger', [], re.findall(
        r'^  (push|pull_request|pull_request_target|schedule|workflow_run|workflow_call|repository_dispatch|merge_group|release|issues|issue_comment):', text, re.M))
    rec.check('harness workflow is dispatched by hand', True, '\non:\n  workflow_dispatch:\n' in text)
    rec.check('harness workflow token is read-only', True, '\npermissions:\n  contents: read\n' in text)
    rec.check('no continue-on-error anywhere in the harness workflow', 0, text.count('continue-on-error'))
    rec.check('no secret is referenced', 0, text.count('secrets.'))
    rec.check('no retry action or retry setting', [], re.findall(r'(?i)retry|max[_-]attempts', text))
    ours, theirs = job_blocks(text), job_blocks(original)
    rec.check('one harness job', [job['harness']], sorted(ours))
    o_header, o_steps = split_job(theirs[job['original']])
    h_header, h_steps = split_job(ours[job['harness']])
    rec.check('the original job runner and 40-minute job timeout are kept and nothing is added to the job', o_header, h_header)
    rec.check('harness step order', job['harness_step_names'], [step_name(step) for step in h_steps])
    kept = [step for step in h_steps if not (step_name(step) or '').startswith('Harness - ')]
    rec.check('every original step is kept, in order', len(o_steps), len(kept))
    applied = []
    for index, (theirs_step, ours_step) in enumerate(zip(o_steps, kept)):
        want = theirs_step
        for old, new in job['allowed_step_changes']:
            if old in want:
                want = want.replace(old, new, 1)
                applied.append(old)
        rec.check('original step %d (%s) is kept verbatim except the registered observation changes' % (index, step_name(theirs_step)), want, ours_step)
    rec.check('each registered observation change applies exactly once', sorted(old for old, _ in job['allowed_step_changes']), sorted(applied))
    harness_steps = [step for step in h_steps if (step_name(step) or '').startswith('Harness - ')]
    timeouts = {}
    for step in harness_steps:
        for match in re.finditer(r'^        timeout-minutes: (\d+)$', step, re.M):
            timeouts[step_name(step)] = int(match.group(1))
    rec.check('harness step timeouts are the registered ones', job['harness_step_timeouts'], timeouts)
    rec.check('only the registered harness steps always run', job['always_harness_steps'], [step_name(s) for s in harness_steps if 'if: always()' in s])
    rec.check('harness steps run only the staged harness', [], [step_name(s) for s in harness_steps if '$RUNNER_TEMP/transport-harness' not in s])
    keys = sorted({m.group(1) for step in h_steps for m in re.finditer(r'^          ([A-Z][A-Z0-9_]*): ', step, re.M)})
    rec.check('step environment names are the registered ones', sorted(job['allowed_env_names']), keys)


# ----------------------------------------------------------------------------------------------------- generated files
def logging_copy(original):
    if original.count(ANCHOR) != 1 or ('\n' + ANCHOR) not in original:
        raise GuardFailure('the proxy template anchor must start exactly one line')
    copy = original.replace(ANCHOR, LOGGING_BLOCK + ANCHOR, 1)
    if copy.count(LOGGING_BLOCK) != 1 or copy.replace(LOGGING_BLOCK, '', 1) != original:
        raise GuardFailure('the generated proxy copy is not the baseline template plus the registered logging block')
    return copy


def generated(original, diag):
    config = diag / 'proxy-config'
    return {
        'proxy-config/default.conf.template': (logging_copy(original).encode('utf-8'), 0o644),
        'proxy-config/99-kin-diag-effective-config.sh': (DUMP_SCRIPT.encode('utf-8'), 0o755),
        OVERRIDE: (OVERRIDE_TEXT.format(template=json.dumps(str(config / 'default.conf.template')),
                                        script=json.dumps(str(config / '99-kin-diag-effective-config.sh')),
                                        logs=json.dumps(str(diag / 'proxy-logs'))).encode('utf-8'), 0o644),
    }


def docker_ids(*args):
    done = subprocess.run(['docker', *args], capture_output=True, timeout=60)
    if done.returncode:
        raise GuardFailure('docker %s exited %d' % (' '.join(args), done.returncode))
    return sorted(done.stdout.decode('utf-8', 'replace').split())


def docker_state(networks=True):
    state = {'containers': docker_ids('ps', '-aq'), 'volumes': docker_ids('volume', 'ls', '-q')}
    if networks:
        state['networks'] = docker_ids('network', 'ls', '--filter', 'type=custom', '-q')
    return state


# -------------------------------------------------------------------------------------------------------- sanitization
def _query(match):
    pairs = []
    for part in match.group(2).split('&'):
        key, sep, value = part.partition('=')
        pairs.append(key + sep + ('[REDACTED]' if value and value != '[REDACTED]' else value))
    return match.group(1) + '?' + '&'.join(pairs)


def sanitize_text(text, query=True):
    counts = {}
    for label, pattern, replacement in (('jwt', JWT, '[REDACTED JWT]'), ('bearer_or_basic', AUTH, r'\1 [REDACTED]'),
                                        ('cookie_or_authorization_header', HEADER, r'\1 [REDACTED]'), ('secret_field', FIELD, r'\1"[REDACTED]"')):
        text, count = pattern.subn(replacement, text)
        counts[label] = count
    if query:
        changed = 0

        def replace(match):
            nonlocal changed
            value = _query(match)
            changed += value != match.group(0)
            return value
        text = QUERY.sub(replace, text)
        counts['query_values'] = changed
    return text, counts


def sanitize_stream(source, target):
    """Line-by-line copy for large text files (NetLog); raw bytes are hashed but never uploaded."""
    raw_hash, clean_hash, counts, size = hashlib.sha256(), hashlib.sha256(), {}, 0
    target.parent.mkdir(parents=True, exist_ok=True)
    with open(source, 'rb') as reader, open(target, 'wb') as writer:
        for raw in reader:
            raw_hash.update(raw)
            text, found = sanitize_text(raw.decode('utf-8', 'replace'))
            data = text.encode('utf-8')
            clean_hash.update(data)
            writer.write(data)
            size += len(data)
            for key, value in found.items():
                counts[key] = counts.get(key, 0) + value
    return {'raw_sha256': raw_hash.hexdigest(), 'sha256': clean_hash.hexdigest(), 'bytes': size, 'redactions': counts}


def read_privileged(path):
    try:
        return path.read_bytes()
    except PermissionError:
        return subprocess.run(['sudo', '-n', 'cat', str(path)], capture_output=True, check=True, timeout=60).stdout


def write_manifest(upload):
    rows = {}
    for path in sorted(p for p in upload.rglob('*') if p.is_file() and p.name != 'manifest.json'):
        digest, size = hashlib.sha256(), 0
        with open(path, 'rb') as stream:
            for chunk in iter(lambda: stream.read(1 << 20), b''):
                digest.update(chunk)
                size += len(chunk)
        rows[path.relative_to(upload).as_posix()] = {'sha256': digest.hexdigest(), 'bytes': size}
    (upload / 'manifest.json').write_text(json.dumps({'written_utc': now(), 'files': rows}, indent=1) + '\n', encoding='utf-8')


# ------------------------------------------------------------------------------------------------------------ commands
def plan(args):
    reg = registry()
    rec = Record('plan')

    def work():
        local_only(rec)
        rec.check('plan runs from the harness worktree root', str(Path.cwd().resolve()), str(Path(out('rev-parse', '--show-toplevel')).resolve()))
        check_registry(rec, reg)
        check_scope(rec, reg)
        # The local worktree's own line-ending configuration decides what is modified here (hosted checks force autocrlf off).
        listed = subprocess.run(['git', 'status', '--porcelain=v1', '--untracked-files=all'], capture_output=True, check=True)
        pending = [row[3:] for row in listed.stdout.decode('utf-8').splitlines()]
        rec.data['uncommitted_paths'] = pending
        rec.check('uncommitted paths are harness paths only', [], [p for p in pending if not allowed(p)])
        text = (Path.cwd() / WORKFLOW).read_bytes().decode('utf-8')
        rec.check('harness workflow on disk has LF line endings', False, '\r' in text)
        check_workflow(rec, reg, text, blob(reg['baseline']['sha'], WORKFLOW).decode('utf-8'))
        template = blob(reg['baseline']['sha'], TEMPLATE).decode('utf-8')
        copy = logging_copy(template)
        rec.data['generated_template_sha256'] = sha256(copy.encode('utf-8'))
        rec.check('the logging block uses no envsubst-filtered name', [], re.findall(
            r'\$\{?(PUBLIC_PORT|PUBLIC_PORT_SUFFIX|SERVER_NAME|TLS_CERTIFICATE|TLS_CERTIFICATE_KEY)', LOGGING_BLOCK))
        rec.check('registered decision rule ids are the analysis rule ids', list(analyze.RULE_IDS), [rule['id'] for rule in reg['decision_rules']])
        crlf, hashes = [], {}
        for path in harness_files():
            data = path.read_bytes()
            hashes[path.relative_to(HERE).as_posix()] = sha256(data)
            if b'\r' in data:
                crlf.append(path.relative_to(HERE).as_posix())
            if path.suffix == '.py':
                with tempfile.TemporaryDirectory() as folder:
                    py_compile.compile(str(path), cfile=str(Path(folder) / 'compiled.pyc'), doraise=True)
        rec.check('harness files have LF line endings', [], crlf)
        rec.data['harness_file_sha256'] = hashes

    rec.run(work)


def generate(args):
    folder = Path(args.out)
    diag = Path('/RUNNER_TEMP') / DIAG_NAME
    for relative, (data, mode) in generated(blob(registry()['baseline']['sha'], TEMPLATE).decode('utf-8'), diag).items():
        target = folder / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
        print('%s %s %o %d' % (sha256(data), relative, mode, len(data)))


def restore(args):
    reg = registry()
    rec = Record('restore')

    def work():
        hosted(rec, reg)
        root = Path.cwd()
        rec.check('staged harness is outside the product checkout', False, HERE.is_relative_to(root.resolve()))
        head = out('rev-parse', 'HEAD')
        rec.check('harness HEAD is the dispatched commit', os.environ.get('GITHUB_SHA'), head)
        rec.data['harness_sha'] = head
        check_staged(rec)
        check_scope(rec, reg)
        check_registry(rec, reg)
        check_workflow(rec, reg, blob('HEAD', WORKFLOW).decode('utf-8'), blob(reg['baseline']['sha'], WORKFLOW).decode('utf-8'))
        rec.check('fresh hosted checkout is clean', '', out('status', '--porcelain=v1', '--untracked-files=all', '--ignored'))
        git('checkout', '--quiet', '--detach', reg['baseline']['sha'])
        rec.check('HEAD is the baseline', reg['baseline']['sha'], out('rev-parse', 'HEAD'))
        rec.check('baseline tree is checked out', reg['baseline']['tree'], out('rev-parse', 'HEAD^{tree}'))
        rec.check('baseline workflow file on disk', reg['baseline']['workflow_blob'], blob_id((root / WORKFLOW).read_bytes()))
        rec.check('no tracked, untracked or ignored difference', '', out('status', '--porcelain=v1', '--untracked-files=all', '--ignored'))
        rec.check('the harness directory is absent from the product checkout', False, (root / HARNESS_DIR).exists())
        rec.check('registered profile sources on disk are the baseline', reg['baseline']['source_sha256'],
                  {path: sha256((root / path).read_bytes()) for path in sorted(reg['baseline']['source_sha256'])})

    rec.run(work, diag_root() / 'harness' / 'restore.json')


def prepare(args):
    reg = registry()
    rec = Record('prepare')
    diag = diag_root()

    def work():
        hosted(rec, reg)
        root = Path.cwd()
        rec.check('restore passed', 'passed', result_of(diag / 'harness' / 'restore.json'))
        rec.check('HEAD is the baseline', reg['baseline']['sha'], out('rev-parse', 'HEAD'))
        rec.check('no tracked difference before observation is prepared', '', out('status', '--porcelain=v1', '--untracked-files=no'))
        rec.data['untracked_before_prepare'] = untracked()
        rec.check('the Docker daemon is still empty', {'containers': [], 'volumes': []}, docker_state(networks=False))
        original = (root / TEMPLATE).read_bytes()
        rec.check('proxy template on disk is the baseline blob', reg['baseline']['proxy_template_blob'], blob_id(original))
        rec.check('no compose override exists before the harness writes one', False, (root / OVERRIDE).exists())
        files = generated(original.decode('utf-8'), diag)
        rec.check('the generated template minus the registered block is the baseline template', sha256(original),
                  sha256(files['proxy-config/default.conf.template'][0].decode('utf-8').replace(LOGGING_BLOCK, '', 1).encode('utf-8')))
        for folder in ('proxy-config', 'proxy-logs', 'browser', 'preflight'):
            (diag / folder).mkdir(parents=True, exist_ok=True)
        # The proxy container's root-run entrypoint and nginx master write here; the runner user collects afterwards.
        os.chmod(diag / 'proxy-logs', 0o777)
        rec.data['generated'] = {}
        for relative, (data, mode) in files.items():
            target = root / relative if relative == OVERRIDE else diag / relative
            target.write_bytes(data)
            os.chmod(target, mode)
            rec.data['generated'][relative] = {'path': str(target), 'sha256': sha256(data), 'bytes': len(data), 'mode': oct(mode)}
        rec.check('tracked tree is still the baseline after the untracked override', '', out('status', '--porcelain=v1', '--untracked-files=no'))
        rec.data['observer_sha256'] = {p.name: sha256(p.read_bytes()) for p in sorted((HERE / 'observer').glob('*.py'))}

    rec.run(work, diag / 'harness' / 'prepare.json')


def preflight(args):
    reg = registry()
    rec = Record('preflight')
    diag = diag_root()
    folder = Path(os.environ.get('KIN_TRANSPORT_DIAG_DIR') or '.')

    def work():
        hosted(rec, reg)
        rec.check('prepare passed', 'passed', result_of(diag / 'harness' / 'prepare.json'))
        rec.check('preflight observer directory', str((diag / 'preflight').resolve()), str(folder.resolve()))
        rec.check('the observer hook directory is first on PYTHONPATH', str((HERE / 'observer').resolve()),
                  str(Path((os.environ.get('PYTHONPATH') or '').split(os.pathsep)[0] or '.').resolve()))
        import kin_transport_observer as observer
        rec.check('the observer was installed by sitecustomize at interpreter start', True, observer.installed())
        from playwright.sync_api import sync_playwright
        with sync_playwright() as playwright:
            browser = playwright.chromium.launch(headless=True, args=['--enable-unsafe-swiftshader'])
            try:
                context = browser.new_context(ignore_https_errors=True)
                context.new_page().goto('data:text/html,<title>kin netlog preflight</title>')
                context.close()
            finally:
                browser.close()
        files = sorted((folder / 'netlog').glob('*.json'))
        rec.data['netlog_files'] = [str(p) for p in files]
        rec.check('one NetLog file for the one launch', 1, len(files))
        capability = analyze.netlog_capability(files[0])
        # The capture mode is the switch the observer itself added (launch record); whether Chromium echoes its command line in
        # the NetLog constants depends on the embedder, so it is recorded, not required.
        rec.data['netlog'] = capability
        rec.check('this Chromium names every event type rule R3 reads', [], capability['missing_event_types'])
        rec.check('the NetLog was written and closed at browser shutdown', True, capability['complete'])

    try:
        rec.run(work, diag / 'harness' / 'preflight.json')
    except Exception:
        traceback.print_exc()
    # The preflight never stops the profile: a failed capture makes the analysis INCONCLUSIVE (rule R1), it does not skip the run.
    return 0


def collect(args):
    reg = registry()
    rec = Record('collect')
    root = Path.cwd()
    upload = root / UPLOAD
    status = {'guard': False, 'analysis': False}

    def work():
        upload.mkdir(parents=True, exist_ok=True)
        diag = diag_root()
        rec.data['files'] = files = []

        def put(relative, data, source, **extra):
            target = upload / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(data)
            files.append({'path': relative, 'source': str(source), 'sha256': sha256(data), 'bytes': len(data), **extra})

        for path in sorted((diag / 'harness').glob('*.json')):
            put('harness/' + path.name, path.read_bytes(), path)
        for path in sorted((diag / 'proxy-config').glob('*')):
            put('generated/' + path.name, path.read_bytes(), path)
        if (root / OVERRIDE).is_file():
            put('generated/' + OVERRIDE, (root / OVERRIDE).read_bytes(), root / OVERRIDE)
        for path in sorted((diag / 'proxy-logs').glob('*')):
            raw = read_privileged(path)
            text, counts = sanitize_text(raw.decode('utf-8', 'replace'), query=path.name != 'nginx-effective-config.txt')
            put('proxy/' + path.name, text.encode('utf-8'), path, raw_sha256=sha256(raw), redactions=counts)
        for folder in ('browser', 'preflight'):
            for path in sorted(p for p in (diag / folder).rglob('*') if p.is_file()):
                relative = folder + '/' + path.relative_to(diag / folder).as_posix()
                files.append({'path': relative, 'source': str(path), **sanitize_stream(path, upload / relative)})
        listing = subprocess.run(['docker', 'ps', '-a', '--format', '{{.Names}}\t{{.Status}}\t{{.Image}}'], capture_output=True, timeout=60)
        put('docker-ps-after-profile.txt', listing.stdout + listing.stderr, 'docker ps -a')
        if 'kin-proxy' in [line.split('\t')[0] for line in listing.stdout.decode('utf-8', 'replace').splitlines()]:
            logs = subprocess.run(['docker', 'logs', '--timestamps', 'kin-proxy'], capture_output=True, timeout=120)
            text, counts = sanitize_text((logs.stdout + logs.stderr).decode('utf-8', 'replace'))
            put('proxy/docker-logs-kin-proxy.log', text.encode('utf-8'), 'docker logs --timestamps kin-proxy', redactions=counts)
        rec.data['restore_result'] = result_of(diag / 'harness' / 'restore.json')
        rec.data['prepare_result'] = result_of(diag / 'harness' / 'prepare.json')
        rec.data['preflight_result'] = result_of(diag / 'harness' / 'preflight.json')
        hosted(rec, reg)
        rec.check('restore passed', 'passed', rec.data['restore_result'])
        rec.check('prepare passed', 'passed', rec.data['prepare_result'])
        rec.check('HEAD is still the baseline', reg['baseline']['sha'], out('rev-parse', 'HEAD'))
        rec.check('no tracked difference after the profile', '', out('status', '--porcelain=v1', '--untracked-files=no'))
        rec.data['untracked_after_profile'] = untracked()
        status['guard'] = True

    try:
        rec.run(work, upload / 'harness' / 'collect.json')
    except Exception:
        traceback.print_exc()
    try:
        result = analyze.analyze(upload, root / PROFILE_OUT)
        (upload / 'analysis.json').write_text(json.dumps(result, ensure_ascii=False, indent=1, default=str) + '\n', encoding='utf-8')
        print('TRANSPORT_DIAGNOSTIC_CLASSIFICATION ' + json.dumps(result['classification'], ensure_ascii=False), flush=True)
        status['analysis'] = True
    except Exception:
        upload.mkdir(parents=True, exist_ok=True)
        (upload / 'analysis-error.txt').write_text(traceback.format_exc(), encoding='utf-8')
        traceback.print_exc()
    write_manifest(upload)
    return 0 if all(status.values()) else 1


def cleanup(args):
    reg = registry()
    rec = Record('cleanup')
    root = Path.cwd()
    upload = root / UPLOAD

    def work():
        hosted(rec, reg)
        rec.data['before'] = before = docker_state()
        if before['containers']:
            rec.data['rm'] = subprocess.run(['docker', 'rm', '--force', *before['containers']], capture_output=True, timeout=90).returncode
        if before['volumes']:
            rec.data['volume_rm'] = subprocess.run(['docker', 'volume', 'rm', '--force', *before['volumes']], capture_output=True, timeout=60).returncode
        for network in before['networks']:
            subprocess.run(['docker', 'network', 'rm', network], capture_output=True, timeout=30)
        if (root / OVERRIDE).is_file():
            (root / OVERRIDE).unlink()
            rec.data['override_removed'] = True
        rec.check('no container, volume or custom network remains on the disposable runner',
                  {'containers': [], 'volumes': [], 'networks': []}, docker_state())
        rec.check('HEAD is still the baseline', reg['baseline']['sha'], out('rev-parse', 'HEAD'))
        rec.check('no tracked difference after cleanup', '', out('status', '--porcelain=v1', '--untracked-files=no'))

    code = 0
    try:
        rec.run(work, upload / 'harness' / 'cleanup.json')
    except Exception:
        traceback.print_exc()
        code = 1
    if upload.is_dir():
        write_manifest(upload)
    return code


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest='command', required=True)
    for name in ('plan', 'restore', 'prepare', 'preflight', 'collect', 'cleanup'):
        sub.add_parser(name)
    sub.add_parser('generate').add_argument('--out', required=True)
    args = parser.parse_args(argv)
    try:
        code = globals()[args.command](args)
    except GuardFailure as error:
        print('HARNESS_REFUSED: ' + str(error), file=sys.stderr)
        return 2
    return code or 0


if __name__ == '__main__':
    sys.exit(main())
